from raw_common import *
Q=[];E=[]
def hi(q,heading,segments,correct):
 q['highlight']={'segments':[token('intro',*heading),*[{**token(*x),'selectable':True} for x in segments]],'correct':correct};Q.append(q)

q=question(2,1,'highlight','Health Promotion and Maintenance','Pediatric & Toddler Safety','recognize_cues',
 ('During a home visit for an18-month-old, the nurse reviews access to button and coin batteries. No ingestion is suspected. Highlight the observations that require immediate removal of a battery hazard from the child’s reach.','家访一名 18 个月幼儿时，护士检查其是否能接触纽扣电池和硬币电池。目前没有疑似吞服事件。标出需要立即从幼儿可及范围内移除电池危险物的观察结果。'),
 ('A loose used battery remains hazardous, and a broken compartment exposes another battery. Both require immediate removal from reach. Secure storage protects against access; a battery being used or depleted does not make it safe to handle.','松散的旧电池仍有危险，破损电池仓也会使电池暴露。两者都应立即移至幼儿无法接触的地方。安全存放可防止接触；电池正在使用或电量耗尽，都不代表幼儿可以安全拿取。'),
 ('Assess whether the child can reach and remove the battery, including one that no longer powers a device.','判断幼儿能否接触并取出电池，也要检查已无法为设备供电的旧电池。'),
 [term('button battery','纽扣电池','可造成严重吞服损伤的小型圆片状电池。'),term('battery compartment','电池仓','设备中容纳电池的部位。')],
 [reason('s1','A locked cabinet prevents the toddler from accessing spare batteries.','上锁柜子可防止幼儿接触备用电池。'),reason('s2','A depleted coin battery can still cause injury if swallowed; the reachable dish is unsafe.','电量耗尽的硬币电池被吞入后仍可能造成损伤；放在幼儿够得到的小碟中并不安全。'),reason('s3','The secured compartment and inaccessible storage address access risk.','固定完好的电池仓加上幼儿无法接触的存放位置，可降低接触风险。'),reason('s4','The damaged cover allows the toddler to reach the battery in a familiar household device.','破损盖子使幼儿能够接触常见家用设备中的电池。'),reason('s5','Prompt secure removal of used batteries keeps them out of the child’s environment.','及时将旧电池妥善移出幼儿活动环境可避免接触。')])
hi(q,('Home observations:','家庭环境观察：'),[('s1','Spare coin batteries are inside a locked cabinet.','备用硬币电池存放在上锁柜子内。'),('s2','A used coin battery lies in a dish on a low table; the caregiver says it is dead.','一枚旧硬币电池放在矮桌的小碟内；照护者说它已经没电了。'),('s3','A thermometer has an intact screw-secured battery cover and is stored in a locked drawer.','体温计电池盖完好并用螺钉固定，体温计存放在上锁抽屉内。'),('s4','A remote control on the play mat has a broken cover, exposing its coin battery.','游戏垫上的遥控器电池盖破损，露出硬币电池。'),('s5','Used batteries awaiting recycling are in a locked container in an area the child cannot enter.','等待回收的旧电池放在上锁容器内，所在区域幼儿无法进入。')],['s2','s4'])
E.append({'id':q['id'],'sourceIds':['cpsc-battery','aap-battery'],'proposition':'Accessible used battery and exposed battery are hazards.','formatDefense':'Two of five; a dead battery is the realistic near-miss. Prevention scenario, not ingestion treatment.'})

q=question(2,2,'dropdown_cloze','Basic Care and Comfort','Palliative & Supportive Care','evaluate_outcomes',
 ('An adult with advanced cancer has persistent breathlessness despite treatment of reversible causes. The palliative team prescribes a monitored trial of low-dose oral morphine for breathlessness. The client also uses a fan and a comfortable supported position. At reassessment, choose the best evidence of symptom benefit and the assessment most directly needed for excessive opioid sedation or respiratory suppression.','一名晚期癌症成人在可逆病因已接受处理后仍持续气促。姑息治疗团队开具低剂量口服吗啡试用方案，要求监测效果，以缓解气促。患者也使用风扇并采取舒适的支撑体位。复评时，选择最能体现症状获益的表现，以及最直接用于发现阿片类药物过度镇静或呼吸抑制的评估。'),
 ('The client’s report that breathing feels easier is direct evidence of symptom relief. Level of arousal and breathing rate/depth address acute opioid sedation and respiratory risk. A saturation change alone does not measure perceived breathlessness, and deep unresponsiveness is not a treatment goal.','患者自述呼吸更轻松，是症状缓解的直接证据。觉醒程度、呼吸频率和深度可用于评估阿片类药物导致的急性镇静及呼吸风险。单凭血氧饱和度变化无法衡量主观气促，无反应的深度镇静也不是治疗目标。'),
 ('Pair the client’s symptom experience with a separate medication-safety assessment.','既关注患者对症状的主观感受，也单独评估用药安全。'),
 [term('breathlessness','气促','主观感受到呼吸不适或费力。'),term('arousal','觉醒程度','对声音或其他刺激作出清醒反应的能力。')],
 [reason('benefit','Easier breathing is the intended symptom benefit. Saturation rising alone may not relieve distress; inability to awaken suggests harm rather than success.','呼吸更轻松是预期症状获益。只有血氧饱和度升高可能并未减轻不适；无法唤醒提示伤害而非治疗成功。'),reason('safety','Arousal and respiratory pattern directly assess acute sedation/respiratory suppression. Bowel function matters for ongoing opioid care but alone cannot detect this acute risk; bruising is not the targeted opioid effect.','觉醒程度和呼吸模式可直接评估急性镇静及呼吸抑制。排便情况对持续阿片治疗很重要，但单独检查排便不能发现此项急性风险；瘀斑也不是此处要监测的阿片作用。')])
q['clozeStem']=pair('Symptom benefit is best shown by {{benefit}}. Assess {{safety}} for the specified acute medication risk.','最能体现症状获益的是 {{benefit}}。为发现所述急性用药风险，应评估 {{safety}}。')
q['dropdowns']=[{'id':'benefit','options':[token('easier','the client reporting that breathing feels easier','患者自述呼吸更轻松'),token('sat','a higher oxygen saturation without a change in distress','血氧饱和度升高但不适程度未变'),token('sleep','the client becoming impossible to awaken','患者变得无法唤醒')],'correct':'easier'},{'id':'safety','options':[token('resp','arousal and respiratory rate and depth','觉醒程度以及呼吸频率和深度'),token('bowel','bowel movement frequency alone','仅排便频率'),token('bruise','the number of old bruises','旧瘀斑的数量')],'correct':'resp'}];Q.append(q)
E.append({'id':q['id'],'sourceIds':['palliative-breathlessness','morphine-warning'],'proposition':'Assess patient-perceived dyspnea benefit and acute respiratory/sedation safety separately.','clinicalBoundary':'Explicit prescribed therapeutic trial; no new dose or guarantee of respiratory safety.'})

q=question(2,3,'highlight','Physiological Adaptation','Sepsis & Septic Shock','evaluate_outcomes',
 ('An adult receiving treatment for sepsis is reassessed after initial resuscitation. The unit tracks mental status, peripheral perfusion, lactate, blood pressure and urine output together. Highlight the trends that show deterioration and need prompt bedside reassessment, even though some other measures are improving.','一名正在接受脓毒症治疗的成人在初始复苏后接受复评。科室结合意识状态、外周灌注、乳酸、血压和尿量进行观察。标出提示恶化、需要立即床旁重新评估的趋势，即使部分其他指标正在改善。'),
 ('New confusion and capillary refill lengthening from2 to5 seconds show deterioration. Falling lactate, rising mean arterial pressure and increasing urine output are improving trends, but do not negate the worsening findings or establish complete recovery.','新出现的意识混乱，以及毛细血管再充盈时间由 2 秒延长到 5 秒，提示情况恶化。乳酸下降、平均动脉压升高和尿量增加属于改善趋势，但不能抵消恶化表现，也不能据此认定已完全恢复。'),
 ('Compare each current finding with its own baseline; improvement in one measure cannot substitute for reassessing another that worsens.','将每项当前结果与其自身先前结果比较；一项改善不能替代对另一项恶化表现的重新评估。'),
 [term('capillary refill','毛细血管再充盈','按压皮肤使其变白后，颜色恢复所需的时间。'),term('perfusion','灌注','血液向组织输送氧和营养物质的过程。')],
 [reason('s1','The lactate is still abnormal but is decreasing; this segment does not show deterioration.','乳酸仍异常，但正在下降；这一片段并未显示恶化。'),reason('s2','New inability to identify the location is a worsening mental-status finding.','新出现的无法辨认所处地点提示意识状态恶化。'),reason('s3','The pressure trend is improving, although it cannot by itself certify adequate perfusion.','血压趋势改善，但不能单独证明灌注已经充分。'),reason('s4','Delayed refill that has worsened under comparable conditions is concerning peripheral-perfusion evidence.','在可比条件下，再充盈时间进一步延长，是需要关注的外周灌注表现。'),reason('s5','Increasing hourly urine output is an improving trend, while continued monitoring remains necessary.','每小时尿量增加属于改善趋势，仍需继续监测。')])
hi(q,('Reassessment compared with the preceding hour:','与前一小时相比的复评记录：'),[('s1','Lactate decreases from3.8 to2.6 mmol/L.','乳酸由 3.8 降至 2.6 mmol/L。'),('s2','The previously fully oriented client now cannot identify the hospital and repeatedly pulls at the IV tubing.','原本定向力完整的患者现在无法辨认自己在医院，并反复拉扯输液管。'),('s3','Mean arterial pressure rises from60 to74 mmHg.','平均动脉压由 60 升至 74 mmHg。'),('s4','Finger capillary refill lengthens from2 to5 seconds using the same technique in the same warm room.','在同一温暖房间用相同方法测量，手指毛细血管再充盈时间由 2 秒延长至 5 秒。'),('s5','Urine output increases from20 to45 mL during successive one-hour intervals.','连续两个一小时时段内，尿量由 20 增至 45 mL。')],['s2','s4'])
E.append({'id':q['id'],'sourceIds':['ssc-2026','lab-ranges'],'proposition':'Worsening mental status and refill warrant reassessment despite improving other measures.','formatDefense':'Two of five; falling but still elevated lactate is a realistic trend-vs-normality near-miss. No single test diagnoses sepsis or proves adequate resuscitation.'})

q=question(2,4,'bowtie','Pharmacological and Parenteral Therapies','Parenteral Nutrition','take_action',
 ('An adult with prolonged minimal intake begins parenteral nutrition through a central line. Thirty-six hours later, the client reports new generalized weakness and breathlessness, with pulse110/min and BP116/72 mmHg. Weight and fluid balance are unchanged; lungs are clear and the catheter site has no inflammation. Blood cultures collected for this change are pending. Phosphate has fallen from3.1 to1.1 mg/dL, potassium from4.0 to2.9 mEq/L and magnesium from1.9 to1.1 mg/dL. Reference intervals are phosphate2.5–4.5 mg/dL, potassium3.5–5.0 mEq/L and magnesium1.7–2.3 mg/dL. For this rapid electrolyte fall, the nutrition team has prescribed electrolyte replacement and a temporary50% reduction in PN dextrose, with cardiac and laboratory monitoring. Select the most likely complication, two actions that address it and two laboratory measures that follow correction of the depleted electrolytes.','一名长期摄入极少的成人通过中心静脉导管开始肠外营养。36 小时后，患者出现全身无力和气促，脉搏 110 次/分，血压 116/72 mmHg。体重和液体平衡未变，双肺呼吸音清晰，导管部位无炎症表现。因本次变化采集的血培养结果尚未报告。血磷由 3.1 降至 1.1 mg/dL，血钾由 4.0 降至 2.9 mEq/L，血镁由 1.9 降至 1.1 mg/dL。参考范围：血磷 2.5–4.5 mg/dL，血钾 3.5–5.0 mEq/L，血镁 1.7–2.3 mg/dL。针对电解质迅速下降，营养团队已开具电解质补充、肠外营养葡萄糖暂时减少 50% 的医嘱，并要求心脏和实验室监测。选择最可能的并发症、两项针对性措施，以及两项用于追踪已降低电解质纠正情况的化验指标。'),
 ('The rapid fall in phosphate, potassium and magnesium after calories are reintroduced strongly supports refeeding syndrome. Implement the prescribed electrolyte replacement and reduced dextrose delivery. Phosphate and potassium trends follow the documented depletion; magnesium also requires monitoring.','重新给予热量后，血磷、血钾和血镁迅速下降，强烈支持再喂养综合征。应执行医嘱的电解质补充与减少葡萄糖输注方案。血磷和血钾趋势可追踪已记录的降低情况；血镁也需要监测。'),
 ('Connect the timing of nutrition with the laboratory pattern before matching corrective actions.','先把营养开始时间与实验室变化联系起来，再匹配纠正措施。'),
 [term('refeeding syndrome','再喂养综合征','长期营养不足者恢复热量摄入后发生的电解质及代谢紊乱。'),term('dextrose','葡萄糖','肠外营养中的一种主要热量来源。')],
 [reason('c_refeed','The synchronized electrolyte drop shortly after nutrition begins is characteristic of refeeding-related depletion.','营养开始后不久多种电解质同步下降，符合再喂养相关的电解质降低。'),reason('c_overload','PN-related fluid overload can cause breathlessness, but stable balance/weight and this electrolyte pattern favor another complication.','肠外营养相关液体过多可导致气促，但稳定的液体平衡和体重，以及这一电解质变化，更支持另一种并发症。'),reason('c_infect','A central line makes infection a competing concern; a normal site does not exclude it. The abrupt post-feeding electrolyte pattern more strongly supports refeeding syndrome.','中心静脉导管使感染成为需要考虑的病因；局部正常不能排除感染。但开始营养后突发的电解质变化更支持再喂养综合征。'),reason('a_replace','Prescribed replacement addresses the measured deficits.','执行医嘱补充可纠正已测得的电解质不足。'),reason('a_reduce','Reducing the prescribed carbohydrate delivery limits ongoing metabolic demand while deficits are corrected.','按医嘱减少碳水化合物输注，可在纠正不足时限制持续增加的代谢需求。'),reason('a_increase','Rapidly increasing calories may worsen refeeding-related electrolyte shifts.','迅速增加热量可能加重再喂养相关电解质转移。'),reason('a_diurese','Empiric diuresis does not replace depleted electrolytes and may worsen potassium/magnesium losses without evidence of congestion.','缺乏充血证据时，经验性利尿不能补充缺失的电解质，还可能加重钾和镁的丢失。'),reason('p_phos','Phosphate directly follows a major documented deficit.','血磷可直接追踪已记录的一项主要不足。'),reason('p_k','Potassium follows the measured fall and response to replacement.','血钾可追踪已测得的下降及补充效果。'),reason('p_a1c','HbA1c reflects longer-term glycemia, not correction of these acute electrolyte deficits.','糖化血红蛋白反映较长期血糖情况，不用于判断本次急性电解质不足是否纠正。'),reason('p_ldl','LDL cholesterol does not track phosphate or potassium replacement.','低密度脂蛋白胆固醇不反映磷或钾的补充效果。')],difficulty='hard')
q['bowtie']={'condition':{'tokens':[token('c_refeed','Refeeding syndrome','再喂养综合征'),token('c_overload','PN-associated fluid overload','肠外营养相关液体过多'),token('c_infect','Catheter-related bloodstream infection','导管相关血流感染')],'correct':'c_refeed'},'actions':{'tokens':[token('a_replace','Administer the prescribed electrolyte replacement','给予医嘱的电解质补充'),token('a_reduce','Implement the prescribed temporary reduction in PN dextrose','执行医嘱，暂时减少肠外营养葡萄糖'),token('a_increase','Increase calories rapidly to correct the weakness','迅速增加热量以纠正无力'),token('a_diurese','Seek a loop diuretic before replacing electrolytes','在补充电解质之前申请袢利尿剂')],'correct':['a_replace','a_reduce']},'parameters':{'tokens':[token('p_phos','Serum phosphate','血磷'),token('p_k','Serum potassium','血钾'),token('p_a1c','Hemoglobin A1c','糖化血红蛋白'),token('p_ldl','LDL cholesterol','低密度脂蛋白胆固醇')],'correct':['p_phos','p_k']}};Q.append(q)
E.append({'id':q['id'],'sourceIds':['aspen-refeeding','nice-nutrition','lab-ranges'],'proposition':'Rapid multi-electrolyte fall after nutrition supports refeeding; execute prescribed replacement and dextrose reduction.','differentialDefense':'Weakness/dyspnea/tachycardia during PN can reflect overload, infection or refeeding; fluid assessment and serial electrolytes resolve the offered alternatives. A clean catheter site does not rule out bloodstream infection.','clinicalBoundary':'Adult, explicit nutrition-team prescription. ASPEN allows individualized reduction/cessation depending on severity; no universal autonomous PN-rate instruction.','reviewAttention':'Independent reviewer must assess differential competitiveness and the scope of parameters. Magnesium is required safety monitoring, not used as a false distractor.'})

q=question(2,5,'highlight','Basic Care and Comfort','Sleep & Rest','recognize_cues',
 ('A client describes poor-quality sleep. Highlight the findings that together most strongly support referral for possible sleep apnea, rather than sleep-hygiene counseling alone.','一名患者诉睡眠质量差。标出共同最有力支持转介评估可能的睡眠呼吸暂停、而不能仅给予睡眠卫生指导的表现。'),
 ('Witnessed breathing pauses with gasping and unintentional daytime sleep episodes despite adequate sleep opportunity support evaluation for sleep apnea. Sleep habits still deserve attention, and these symptoms do not replace a diagnostic sleep evaluation.','被目击的呼吸暂停伴喘息，以及有足够睡眠机会却仍在白天不自主入睡，支持进行睡眠呼吸暂停评估。睡眠习惯仍需关注，这些症状也不能替代诊断性睡眠评估。'),
 ('Look for impaired breathing during sleep paired with daytime functional effects.','寻找睡眠时呼吸受损与白天功能受影响相结合的表现。'),
 [term('sleep apnea','睡眠呼吸暂停','睡眠过程中反复出现呼吸停止和恢复的情况。'),term('daytime sleepiness','日间嗜睡','白天难以保持清醒或不自主入睡。')],
 [reason('s1','Evening screen use can affect sleep habits but does not directly establish breathing pauses.','晚间使用屏幕可影响睡眠习惯，但不能直接证明存在呼吸暂停。'),reason('s2','Repeated pauses followed by gasping are characteristic breathing symptoms that warrant evaluation.','反复呼吸暂停后喘息是值得评估的典型呼吸症状。'),reason('s3','A comfortable dark room supports sleep and is not a sign of disordered breathing.','舒适、昏暗的房间有助睡眠，并不是呼吸紊乱表现。'),reason('s4','Repeated unintended sleep during the day despite adequate opportunity for sleep is a meaningful functional symptom.','有足够睡眠机会却反复在白天不自主入睡，是有意义的功能性症状。'),reason('s5','Brief awakening followed by prompt return to sleep alone does not carry the same apnea-specific concern.','短暂醒来后很快重新入睡，单独并不具有相同的睡眠呼吸暂停特异性警示意义。')])
hi(q,('Sleep interview:','睡眠访谈：'),[('s1','The client sometimes watches television shortly before bedtime.','患者有时在临睡前看电视。'),('s2','The partner observes repeated breathing pauses followed by loud gasps during sleep.','伴侣观察到患者睡眠时反复呼吸暂停，随后大声喘气。'),('s3','The bedroom is dark and at a comfortable temperature.','卧室昏暗，温度舒适。'),('s4','Despite allowing eight hours for sleep nightly, the client repeatedly dozes unintentionally during daytime meetings.','尽管每晚留出八小时睡眠时间，患者仍在白天开会时反复不自主打瞌睡。'),('s5','The client sometimes awakens briefly when turning over and returns to sleep promptly.','患者有时翻身时短暂醒来，随后很快重新入睡。')],['s2','s4'])
E.append({'id':q['id'],'sourceIds':['nhlbi-apnea'],'proposition':'Breathing pauses/gasps plus functional daytime sleepiness warrant evaluation.','formatDefense':'Two of five; late TV use is a sleep-hygiene near-miss. No definitive diagnosis from symptoms alone.'})

q=question(2,6,'highlight','Psychosocial Integrity','Substance Use & Withdrawal','recognize_cues',
 ('A hospitalized adult is being treated for alcohol withdrawal. The unit protocol calls for immediate medical reassessment for new disorientation, hallucinations or seizures. Highlight the new findings that meet this escalation rule.','一名住院成人正在接受酒精戒断治疗。科室规程要求：出现新的定向障碍、幻觉或癫痫发作时，立即请医疗团队重新评估。标出符合这一升级处理规则的新表现。'),
 ('New disorientation and seeing insects that are not present meet the escalation criteria and may indicate progression to severe withdrawal. Mild tremor, nausea and anxiety still require treatment and monitoring, but do not by themselves meet this stated rule.','新出现的定向障碍以及看到并不存在的昆虫，符合升级处理标准，可能提示向重度戒断进展。轻度震颤、恶心和焦虑仍需要治疗及监测，但单独并不符合题干所列规则。'),
 ('Separate common withdrawal symptoms from a new change in orientation or perception.','区分常见戒断症状与新出现的定向力或知觉改变。'),
 [term('hallucination','幻觉','不存在相应外部刺激时产生的知觉体验。'),term('withdrawal','戒断','减少或停止长期使用的物质后出现的症状。')],
 [reason('s1','A mild fine tremor needs ongoing withdrawal care but does not meet the listed escalation findings.','轻度细微震颤需要持续戒断护理，但不符合所列升级处理表现。'),reason('s2','New inability to identify place represents disorientation and triggers reassessment.','新出现的无法辨认地点属于定向障碍，触发重新评估。'),reason('s3','Mild nausea without vomiting is a common symptom to treat, not one of the specified new severe findings.','无呕吐的轻度恶心是需要处理的常见症状，并非所列新出现的严重表现。'),reason('s4','Seeing nonexistent insects is a visual hallucination, even if the client can describe it clearly.','看到不存在的昆虫属于视幻觉，即使患者能清楚描述这一体验也一样。'),reason('s5','Expressing anxiety while remaining oriented does not by itself meet the stated escalation rule.','仍有完整定向力时表达焦虑，单独并不符合题干所列升级处理规则。')])
hi(q,('Current assessment:','当前评估：'),[('s1','A fine hand tremor remains mild.','双手细微震颤仍为轻度。'),('s2','After being oriented earlier, the client now insists the hospital room is a railway station.','患者先前定向力完整，现在却坚称病房是火车站。'),('s3','The client reports mild nausea without vomiting.','患者诉轻度恶心，无呕吐。'),('s4','The client points to insects crawling on the wall that staff confirm are not present.','患者指着墙上爬行的昆虫，但工作人员确认墙上并无昆虫。'),('s5','When asked about an earlier symptom, the client describes feeling worried while still knowing the date and location.','被问及先前症状时，患者描述当时感到担忧，但仍知道日期和所处地点。')],['s2','s4'])
E.append({'id':q['id'],'sourceIds':['alcohol-withdrawal'],'proposition':'New disorientation and hallucination trigger specified escalation.','formatDefense':'Two of five; common mild symptoms are plausible near-misses. The anxiety segment is explicitly an earlier report, preventing contradiction with current disorientation.','clinicalBoundary':'No forced treatment sequence or sedative dosing.'})
save(2,Q,E)
