import pathlib,json,hashlib,subprocess
R=pathlib.Path(__file__).resolve().parents[1];C=R/'phase-c'
S=[]
def source(id,title,url,locator,support,limitations='Supports the indicated clinical facts, not independent certification of the raw item.'):
 S.append(dict(id=id,title=title,url=url,locator=locator,accessed='2026-09-12',support=support,limitations=limitations))
source('arithmetic','Explicit authored orders and dimensional arithmetic',None,'t1_01; t3_02','675/4.5=150mL/hr; 500×20/200=50gtt/min.','Scenario amounts and orders are fictional inputs, not treatment recommendations. No external conversion needed for minutes/hours.')
source('ect-recovery','RDaSH ECT clinical guidelines policy','https://www.rdash.nhs.uk/policies/electroconvulsive-therapy-clinical-guidelines-policy/','Recovery monitoring; physical observations; memory and cognition during treatment','Supports post-anesthetic monitoring and continued cognition assessment.','The t1_02 numeric reassessment trigger is an explicit fictional unit rule, not an asserted universal ECT cutoff. Independent reviewer must assess its suitability.')
source('ect-side-effects','Oxford Health NHS ECT side effects','https://oxfordhealth.nhs.uk/ips/ect/what-are-the-side-effects-of-ect/','Short-term effects; memory effects','Mild headache, nausea and confusion can occur; some memory gaps persist. No incidence or guaranteed recovery time is imported.')
source('cdc-chc','CDC U.S. MEC combined hormonal contraceptives','https://www.cdc.gov/contraception/hcp/usmec/combined-hormonal-contraceptives.html','DVT/PE without anticoagulation; migraine with aura; superficial venous disorders; breast disease','Idiopathic prior DVT without current anticoagulation and migraine with aura are category 4; family breast-cancer history and uncomplicated varicose veins are not those exclusions.')
source('abg-ranges','MedlinePlus arterial blood gas test','https://medlineplus.gov/lab-tests/arterial-blood-gas-abg-test/','Normal reference ranges; pH/PaCO2/HCO3 interpretation','pH7.35–7.45, PaCO2 35–45mmHg and ABG HCO3 22–26mEq/L agree with the repository reference-range lane.','Range owner cross-check: src/visuals/kinds/lab_trend/defs.ts ph/paco2/hco3_abg; audit/lab-reference-range-verification-2026-07-19.md S20. Arterial bicarbonate interval is distinct from chemistry bicarbonate.')
source('dka-consensus','ADA/EASD/JBDS/AACE/DTS 2024 hyperglycaemic crises consensus','https://pmc.ncbi.nlm.nih.gov/articles/PMC11343900/','Diagnostic criteria; fluids; insulin/potassium; bicarbonate; resolution; special populations','DKA requires diabetes/hyperglycemia with ketosis and acidosis; euglycemic DKA has glucose<200mg/dL. Fluids and insulin with potassium safeguards treat DKA. Follow blood ketones and acidosis for resolution.','Same consensus co-publication: https://pmc.ncbi.nlm.nih.gov/articles/PMC11272983/ . Direct PMC open intermittently returned a browser challenge; primary-source indexed sections were retrievable and checked. Do not count the two publications as independent evidence.')
source('acog-fhr','ACOG Countdown to Intern Year week4: fetal heart tracings','https://www.acog.org/community/districts-and-sections/district-iv/whats-new/countdown-to-intern-year-week-4-fetal-heart-tracings','Definitions of baseline, variability, late decelerations and tachysystole','US-style excessive frequency is >5 contractions/10min averaged over30min; delayed slowing relative to contraction describes late decelerations.')
source('nice-fhr','NICE NG229 fetal monitoring recommendations','https://www.nice.org.uk/guidance/NG229/chapter/recommendations','Conservative measures; excessive contraction frequency','Supports reducing/stopping oxytocin as part of response to contraction/fetal-heart concerns.','Used for action support only; do not substitute NICE’s differently worded frequency definition for the explicit US-style rule in the question.')
source('cpsc-battery','US CPSC button cell and coin batteries','https://www.cpsc.gov/Safety-Education/Safety-Education-Centers/Button-Cell-Coin-Battery-Information-Center','Safety tips: compartments, damaged covers, storage','Accessible batteries and damaged battery compartments require protection/removal from children’s reach.')
source('aap-battery','American Academy of Pediatrics battery safety','https://www.healthychildren.org/English/safety-prevention/at-home/Pages/What-Parents-Need-to-Know-about-Button-and-Lithium-Coin-Batteries.aspx','Secure storage; used batteries','Used/depleted batteries can remain dangerous; secure compartments and inaccessible storage matter.')
source('palliative-breathlessness','Scottish Palliative Care Guidelines: breathlessness','https://www.rightdecisions.scot.nhs.uk/scottish-palliative-care-guidelines/symptom-management/breathlessness/','Non-drug measures; opioid therapeutic trial','Supports fan/positioning and a monitored opioid trial with response/side-effect assessment.','No claim that low-dose opioids cannot cause respiratory depression; no dose imported.')
source('morphine-warning','DailyMed morphine sulfate oral solution label','https://dailymed.nlm.nih.gov/dailymed/fda/fdaDrugXsl.cfm?setid=ca359246-4674-4b32-b8b2-673d32b7112f','Boxed warning; respiratory depression and sedation','Opioid initiation and dose increases require attention to respiratory depression and sedation.','Label supports adverse-effect monitoring, not an on-label claim for breathlessness.')
source('ssc-2026','Surviving Sepsis Campaign 2026 adult guidelines','https://www.sccm.org/clinical-resources/guidelines/guidelines/surviving-sepsis-campaign-international-guidelines-for-management-of-sepsis-and-septic-shock-2026','Perfusion assessment; lactate; capillary refill; clinical diagnosis','Use multiple perfusion measures; capillary refill is an adjunct, and sepsis is not established/excluded by a single biomarker.','Authored trend values are scenario measurements, not new universal thresholds.')
source('lab-ranges','Repository source-verified adult lab reference lane',None,'src/visuals/kinds/lab_trend/defs.ts; audit/lab-reference-range-verification-2026-07-19.md','Cross-checked phosphate2.5–4.5mg/dL, K3.5–5.0mEq/L, Mg1.7–2.3mg/dL and lactate0.5–2.0mmol/L.','These explicit intervals do not imply every laboratory uses identical intervals.')
source('aspen-refeeding','ASPEN consensus recommendations for refeeding syndrome','https://aspenjournals.onlinelibrary.wiley.com/doi/10.1002/ncp.10474','Definition; Table6 adult treatment and monitoring','Rapid phosphate/potassium/magnesium decline after caloric reintroduction supports refeeding. Replace deficits; individualize caloric reduction/cessation according to severity.','The question uses an explicit nutrition-team prescription; the producer does not assert an autonomous or universally appropriate50% PN adjustment.')
source('nice-nutrition','NICE CG32 nutrition support','https://www.nice.org.uk/guidance/cg32/chapter/recommendations','1.4.6–1.4.8; Table2 monitoring','Prolonged low intake increases refeeding risk; skilled nutrition management and electrolyte monitoring/repletion are needed.')
source('nhlbi-apnea','NHLBI sleep apnea symptoms','https://www.nhlbi.nih.gov/health/sleep-apnea/symptoms','Symptoms and diagnosis','Breathing pauses/gasping and daytime sleepiness support evaluation; symptoms alone do not substitute for diagnostic testing.')
source('alcohol-withdrawal','MedlinePlus alcohol withdrawal','https://www.medlineplus.gov/ency/article/000764.htm','Symptoms; severe withdrawal; emergency assessment','New severe confusion, hallucinations or seizures can indicate severe withdrawal and require urgent assessment.')
source('cdc-hand-hygiene','CDC clinical safety: hand hygiene for healthcare workers','https://www.cdc.gov/clean-hands/hcp/clinical-safety/index.html','Indications; after glove removal','Hand hygiene is required after glove/PPE removal; gloves do not replace it.')
source('cdc-lam','CDC U.S. MEC lactational amenorrhea method','https://www.cdc.gov/contraception/hcp/usmec/lactational-amenorrhea-method.html','All three eligibility conditions','All required: amenorrhea, <6months postpartum and fully/nearly fully breastfeeding without intervals beyond4h by day/6h at night.')
(C/'sources.json').write_text(json.dumps(S,ensure_ascii=False,indent=2)+'\n')
owners=['BANK-CENSUS.md','census.json','gpt-evergreen-generation-prompt.md','NCLEX-Question-Schema.md','src/types.ts','src/schema.ts','src/grading.ts','src/topics.ts','src/visuals/kinds/lab_trend/defs.ts','audit/lab-reference-range-verification-2026-07-19.md']
state={'basis':'Local disk on accepted-mainline derivative; current sources reread before planning','baseHead':subprocess.check_output(['git','rev-parse','HEAD'],text=True).strip(),'scoredLeaves':2535,'standaloneLeaves':1804,'embeddedLeaves':731,'underServedCategories':[],'underServedFormats':{'bowtie':162,'highlight':209,'fill_in_blank':220,'ordered_response':245,'dropdown_cloze':288},'censusGenerated':'2026-09-11T05:49:37.169Z','hashes':{p:hashlib.sha256(pathlib.Path(p).read_bytes()).hexdigest() for p in owners},'ownerOverrides':['Campaign commission expressly permits up to3 batches in this run.','Disk-enabled local executor may read the explicit accepted-mainline worktree and run validators; the standalone web-chat prompt’s cannot-validate wording does not describe this environment.'],'noCases':True,'noVisuals':True,'noPediatricBurns':True,'unreviewed':True}
(C/'planning-inputs.json').write_text(json.dumps(state,indent=2)+'\n')
print(f'Source registry: {len(S)} sources; planning inputs hashed')
