from raw_common import *
Q=[];E=[]
q=question(1,1,'fill_in_blank','Pharmacological and Parenteral Therapies','IV Fluid Calculations','take_action',
 ('A 1,000-mL bag of 0.9% sodium chloride has delivered 325 mL. After reassessing the client, the prescriber orders the remaining volume to infuse over the next 4 hours 30 minutes. Enter the remaining volume and the pump rate for this new order. Use whole numbers.','一袋 1,000 mL 的 0.9% 氯化钠溶液已输入 325 mL。重新评估患者后，处方者开具新医嘱：将剩余液体在接下来的 4 小时 30 分钟内输完。填写剩余液量和执行新医嘱所需的输液泵速度，均用整数。'),
 ('Remaining volume is 1,000 − 325 = 675 mL. The new interval is 4.5 hours, so 675 ÷ 4.5 = 150 mL/hr. The calculation follows a newly prescribed interval; it is not an automatic catch-up adjustment.','剩余液量为 1,000 − 325 = 675 mL。新的输注时长为 4.5 小时，因此 675 ÷ 4.5 = 150 mL/hr。这是依据新医嘱计算速度，并非自行加速以补回延误。'),
 ('Subtract the amount already infused, then convert the entire remaining interval to hours.','先减去已输入的液量，再把新的输注时长统一换算为小时。'),
 [term('remaining volume','剩余液量','尚未输入患者体内的液体量。'),term('infusion rate','输注速度','单位时间内输入的液量。')],
 [reason('volume','The original bag volume includes the 325 mL already delivered; subtract it once.','原袋液量包含已输入的 325 mL，应将其减去一次。'),reason('rate','Thirty minutes equals half an hour, not 0.30 hour; divide 675 by 4.5.','30 分钟等于半小时，不是 0.30 小时；用 675 除以 4.5。')])
q['blanks']=[{'id':'volume','prompt':pair('Remaining mL','剩余 mL'),'numeric':{'value':675,'tolerance':0,'unit':'mL'}},{'id':'rate','prompt':pair('Pump rate in mL/hr','泵速，mL/hr'),'numeric':{'value':150,'tolerance':0,'unit':'mL/hr'}}];Q.append(q)
E.append({'id':q['id'],'sourceIds':['arithmetic'],'proposition':'Apply the explicit revised infusion order;675mL/4.5h=150mL/h.','fictionalInputs':'Bag amount, delivered amount and revised prescription are authored scenario inputs; no clinical dose recommendation.','formatDefense':'Two finite numeric outputs; no sequence or differential is forced.'})

q=question(1,2,'highlight','Psychosocial Integrity','Electroconvulsive Therapy (ECT)','recognize_cues',
 ('An adult is in supervised recovery immediately after ECT under general anesthesia. The recovery protocol calls for immediate anesthesia reassessment for recurrent airway obstruction or oxygen saturation below 92%. Highlight the findings that meet these criteria, rather than expected transient recovery effects.','一名成人在全身麻醉下接受电休克治疗（ECT）后，正在有人监护的恢复区观察。恢复区规程要求：若出现反复气道梗阻或血氧饱和度低于 92%，立即请麻醉团队重新评估。标出符合这些标准的表现，而不是预期的短暂恢复期反应。'),
 ('Recurrent obstruction and saturation of 88% require prompt airway/oxygenation reassessment. Brief disorientation, mild headache and mild nausea can occur after ECT and anesthesia, but still need observation and symptom care.','反复气道梗阻和血氧饱和度 88% 需要立即重新评估气道与氧合。短暂定向障碍、轻度头痛和轻度恶心可见于 ECT 及麻醉后，但仍须观察并给予相应护理。'),
 ('Separate threats to breathing from common short-lived discomforts.','区分危及呼吸的表现与常见的短暂不适。'),
 [term('airway obstruction','气道梗阻','气流通过气道受到阻碍。'),term('disorientation','定向障碍','对时间、地点或人物的辨认暂时受损。')],
 [reason('s1','Asking where the client is while awakening can reflect transient confusion; it does not meet the stated respiratory trigger.','苏醒时询问自己在哪里可属于短暂意识混乱，不符合题干规定的呼吸警示标准。'),reason('s2','Repeated snoring obstruction despite repositioning is an airway problem, not simply normal sleepiness.','调整体位后仍反复出现鼾声伴气流受阻提示气道问题，不能仅归为正常困倦。'),reason('s3','A mild headache can follow ECT and warrants comfort measures without being the specified anesthesia emergency.','ECT 后可出现轻度头痛，应采取舒适护理，但这并非所列麻醉急症标准。'),reason('s4','Saturation of 88% is below the explicit92% trigger and requires immediate reassessment.','血氧饱和度 88% 低于题干明确规定的 92% 警示值，需要立即重新评估。'),reason('s5','Mild nausea without vomiting can be treated and monitored; it is not either specified breathing criterion.','无呕吐的轻度恶心可给予处理并观察，不符合题干列出的两项呼吸标准。')])
q['highlight']={'segments':[token('intro','Recovery note:','恢复区记录：'),*[{**token(*x),'selectable':True} for x in [('s1','The client awakens to voice and asks where they are.','患者听到呼唤后醒来，询问自己在哪里。'),('s2','Snoring with obstructed airflow recurs after repositioning; the nurse is supporting the airway.','调整体位后再次出现鼾声伴气流受阻；护士正在维持气道通畅。'),('s3','The client rates a headache2/10.','患者自述头痛评分为 2/10。'),('s4','Oxygen saturation is88% with a reliable pulse-oximeter waveform.','脉搏血氧仪波形可靠，血氧饱和度为 88%。'),('s5','The client reports mild nausea without vomiting.','患者诉轻度恶心，无呕吐。')]]],'correct':['s2','s4']};Q.append(q)
E.append({'id':q['id'],'sourceIds':['ect-recovery','ect-side-effects'],'proposition':'Identify two respiratory safety triggers during ECT recovery.','fictionalInputs':'The92% reassessment trigger is an explicit authored local protocol, not a universal ECT threshold.','formatDefense':'Two of five selectable findings; transient confusion is a clinically plausible near-miss.'})

q=question(1,3,'highlight','Health Promotion and Maintenance','Reproductive & Endocrine Health','recognize_cues',
 ('A28-year-old requests a combined estrogen-progestin contraceptive pill. The clinic follows U.S. MEC guidance: migraine with aura and a prior unprovoked deep-vein thrombosis in a person no longer taking anticoagulation make this method an unacceptable health risk. Highlight the history findings that meet those criteria.','一名 28 岁女性希望使用雌激素与孕激素复方口服避孕药。诊所遵循美国避孕医学适用标准：有先兆偏头痛，以及既往发生无明确诱因的深静脉血栓且目前未接受抗凝治疗，均使此类避孕方法具有不可接受的健康风险。标出符合这些标准的病史。'),
 ('The documented visual aura and prior unprovoked DVT require a different contraceptive plan. A family history of breast cancer, treated menstrual cramps and stable uncomplicated varicose veins do not equal those contraindicating histories.','有记录的视觉先兆及既往无明确诱因的深静脉血栓提示需要选择其他避孕方案。乳腺癌家族史、经处理的痛经及稳定且无并发症的静脉曲张，不等同于有先兆偏头痛或深静脉血栓病史。'),
 ('Distinguish the client’s own vascular/neurologic history from family history or superficial vein changes.','区分患者本人的血管及神经系统病史、家族史与浅表静脉改变。'),
 [term('migraine with aura','有先兆偏头痛','头痛前后伴特定局灶性神经症状的偏头痛类型。'),term('unprovoked DVT','无明确诱因的深静脉血栓','未发现手术、创伤等暂时诱因的深静脉血栓。')],
 [reason('s1','A mother’s breast cancer is family history, not the client having current breast cancer.','母亲患乳腺癌属于家族史，不等于患者本人当前患乳腺癌。'),reason('s2','A neurologist-documented visual aura meets the migraine-with-aura criterion.','神经科医生记录的视觉先兆符合有先兆偏头痛这一标准。'),reason('s3','Uncomplicated stable varicose veins are distinct from a history of deep venous thrombosis.','稳定且无并发症的静脉曲张不同于深静脉血栓病史。'),reason('s4','The unprovoked deep clot with completed anticoagulation meets the stated high-risk history.','既往无明确诱因的深静脉血栓，且已结束抗凝治疗，符合题干所述高风险病史。'),reason('s5','Menstrual cramps responsive to ibuprofen do not establish either listed contraindication.','布洛芬可缓解的痛经并不符合题干列出的禁忌标准。')])
q['highlight']={'segments':[token('intro','Contraceptive history:','避孕咨询病史：'),*[{**token(*x),'selectable':True} for x in [('s1','My mother was treated for breast cancer at age60; I have never had breast cancer.','我母亲 60 岁时接受过乳腺癌治疗，我本人从未患乳腺癌。'),('s2','My neurologist diagnosed migraine with visual aura: zigzag lights precede the headache.','神经科医生诊断我有视觉先兆偏头痛：头痛前会看到锯齿状闪光。'),('s3','I have longstanding painless varicose veins with no superficial clot or inflammation.','我长期有无痛性静脉曲张，没有浅表血栓或炎症。'),('s4','I had an unprovoked DVT two years ago and completed anticoagulation; I take no anticoagulant now.','两年前我曾发生无明确诱因的深静脉血栓，已完成抗凝疗程，目前不服抗凝药。'),('s5','My regular menstrual cramps improve with ibuprofen.','我平时的痛经服用布洛芬后可缓解。')]]],'correct':['s2','s4']};Q.append(q)
E.append({'id':q['id'],'sourceIds':['cdc-chc'],'proposition':'Apply stated estrogen-method eligibility exclusions.','formatDefense':'Two specific histories among five; family cancer history and superficial venous disease are real near-misses.'})

q=question(1,4,'dropdown_cloze','Reduction of Risk Potential','ABG & Acid-Base Interpretation','analyze_cues',
 ('An adult breathing rapidly before a procedure has an arterial blood gas: pH7.49, PaCO₂30mmHg, HCO₃⁻22mEq/L. The laboratory reference intervals are pH7.35–7.45, PaCO₂35–45mmHg and HCO₃⁻22–26mEq/L. Interpret the primary acid-base pattern.','一名成人在操作前呼吸急促。动脉血气结果：pH 7.49、PaCO₂ 30 mmHg、HCO₃⁻ 22 mEq/L。实验室参考范围为 pH 7.35–7.45、PaCO₂ 35–45 mmHg、HCO₃⁻ 22–26 mEq/L。判断主要酸碱紊乱类型。'),
 ('The elevated pH indicates alkalemia, and the reduced PaCO₂ identifies a respiratory alkalosis. Bicarbonate is within the supplied interval; there is no bicarbonate elevation to explain a primary metabolic alkalosis.','pH 升高提示碱血症，PaCO₂ 降低提示呼吸性碱中毒。碳酸氢根位于题干给定范围内，未见可解释原发性代谢性碱中毒的升高。'),
 ('Classify the pH first, then identify which component moves in the direction that explains it.','先判断 pH 的方向，再找出能解释这一变化的成分。'),
 [term('alkalemia','碱血症','血液 pH 高于正常范围。'),term('PaCO₂','动脉血二氧化碳分压','反映肺部二氧化碳排出情况的指标。')],
 [reason('pattern','Respiratory alkalosis fits alkalemia with low PaCO₂. Respiratory acidosis requires an acidifying CO₂ rise; metabolic alkalosis would be driven by elevated bicarbonate.','碱血症伴 PaCO₂ 降低符合呼吸性碱中毒。呼吸性酸中毒应由二氧化碳升高导致酸化；代谢性碱中毒则由碳酸氢根升高驱动。'),reason('driver','Reduced PaCO₂ explains the alkaline shift. The pH indicates its direction, while bicarbonate22 is not elevated and cannot be the proposed metabolic driver.','PaCO₂ 降低解释了向碱性的变化。pH 说明变化方向；碳酸氢根 22 并未升高，不能作为所述代谢性驱动因素。')])
q['clozeStem']=pair('The primary pattern is {{pattern}}, supported by {{driver}}.','主要紊乱为 {{pattern}}，其依据是 {{driver}}。');q['dropdowns']=[{'id':'pattern','options':[token('ralk','respiratory alkalosis','呼吸性碱中毒'),token('racid','respiratory acidosis','呼吸性酸中毒'),token('malk','metabolic alkalosis','代谢性碱中毒')],'correct':'ralk'},{'id':'driver','options':[token('co2','the PaCO₂ below its reference interval','PaCO₂ 低于参考范围'),token('hco3','an elevated bicarbonate concentration','碳酸氢根浓度升高'),token('ph','an acidic pH','pH 呈酸性')],'correct':'co2'}];Q.append(q)
E.append({'id':q['id'],'sourceIds':['abg-ranges'],'proposition':'Respiratory alkalosis; do not infer anxiety as sole cause.','rangeOwner':'src/visuals/kinds/lab_trend/defs.ts:ph,paco2,hco3_abg; audit/lab-reference-range-verification-2026-07-19.md:S20','physiologyCheck':'Henderson–Hasselbalch approximation6.1+log10(22/(0.03*30))≈7.49.'})

q=question(1,5,'bowtie','Physiological Adaptation','Diabetic Ketoacidosis (DKA)','take_action',
 ('An adult with type2 diabetes reports five days of poor intake, thirst, frequent urination and worsening nausea. The client is alert with dry mucosa, pulse112/min and BP102/64mmHg; there is no heart or kidney failure. Labs show glucose480mg/dL, β-hydroxybutyrate5.8mmol/L, venous pH7.20, bicarbonate12mEq/L and potassium4.2mEq/L; urine output is present. The emergency protocol uses isotonic crystalloid and IV insulin for ketoacidosis; insulin is delayed if potassium is below3.5mEq/L, and bicarbonate is considered only for pH below7.0. Applicable orders are available. Select the best-supported condition, two immediate treatment actions and two parameters that track resolution of ketoacidosis.','一名 2 型糖尿病成人诉近五天进食少、口渴、尿频和逐渐加重的恶心。患者神志清楚，黏膜干燥，脉搏 112 次/分，血压 102/64 mmHg，无心力衰竭或肾衰竭。化验：血糖 480 mg/dL、β-羟丁酸 5.8 mmol/L、静脉血 pH 7.20、碳酸氢根 12 mEq/L、血钾 4.2 mEq/L；患者仍有尿量。急诊规程规定，酮症酸中毒使用等渗晶体液和静脉胰岛素治疗；血钾低于 3.5 mEq/L 时延迟胰岛素治疗，仅在 pH 低于 7.0 时考虑碳酸氢盐。相关医嘱已开具。选择证据最充分的病情、两项立即治疗措施，以及两项用于追踪酮症酸中毒消退的指标。'),
 ('Hyperglycemia with marked ketonemia and acidosis supports DKA. Isotonic fluid and prescribed insulin address volume depletion and ketone production with potassium monitoring. Falling blood ketones and recovery of venous pH track resolution; glucose improvement alone is insufficient.','高血糖、显著酮血症及酸中毒支持 DKA。等渗补液与医嘱胰岛素分别处理容量不足及酮体生成，同时需监测血钾。血酮下降与静脉血 pH 恢复可追踪病情消退；仅血糖改善并不充分。'),
 ('Use the laboratory pattern to distinguish overlapping dehydration symptoms, then match treatment and resolution measures.','用实验室结果区分具有相似脱水症状的疾病，再匹配治疗和缓解指标。'),
 [term('ketonemia','酮血症','血液中酮体增多。'),term('isotonic crystalloid','等渗晶体液','用于细胞外液及血管内容量补充的一类溶液。')],
 [reason('c_dka','Marked ketonemia plus acidosis in diabetes supports DKA.','糖尿病患者显著酮血症合并酸中毒支持 DKA。'),reason('c_hhs','HHS also causes thirst and dehydration, but this marked ketosis/acidosis is inconsistent with isolated HHS.','HHS 也会导致口渴和脱水，但如此明显的酮症及酸中毒不符合单纯 HHS。'),reason('c_starve','Poor intake can produce starvation ketosis, but marked hyperglycemia in diabetes with this degree of ketonemia favors DKA.','摄入不足可引起饥饿性酮症，但糖尿病患者的明显高血糖及这一程度的酮血症更支持 DKA。'),reason('a_fluid','Isotonic fluid treats the documented volume deficit.','等渗液可纠正已记录的容量不足。'),reason('a_insulin','Insulin suppresses ketone production; current potassium meets the supplied start criterion.','胰岛素抑制酮体生成；当前血钾符合给定的启动标准。'),reason('a_bicarb','The current pH does not meet the stated bicarbonate criterion.','当前 pH 未达到所列使用碳酸氢盐的标准。'),reason('a_delay','Waiting for oral tolerance leaves active ketoacidosis untreated.','等到能口服进食才开始治疗，会使正在发生的酮症酸中毒得不到处理。'),reason('p_ketone','Blood β-hydroxybutyrate directly follows the ketone burden.','血 β-羟丁酸直接反映酮体负荷。'),reason('p_ph','Venous pH follows recovery from acidemia.','静脉血 pH 可追踪酸血症的改善。'),reason('p_inr','INR assesses coagulation rather than ketoacidosis resolution.','INR 评估凝血情况，不用于判断酮症酸中毒是否消退。'),reason('p_tsh','TSH evaluates thyroid signaling, not clearance of ketones or correction of this acidosis.','TSH 反映甲状腺调控情况，不用于判断酮体清除或本次酸中毒纠正。')],difficulty='hard')
q['bowtie']={'condition':{'prompt':pair('Most likely condition','最可能的病情'),'tokens':[token('c_dka','Diabetic ketoacidosis','糖尿病酮症酸中毒'),token('c_hhs','Isolated hyperosmolar hyperglycemic state','单纯高渗高血糖状态'),token('c_starve','Starvation ketosis','饥饿性酮症')],'correct':'c_dka'},'actions':{'tokens':[token('a_fluid','Begin the prescribed isotonic crystalloid','开始医嘱的等渗晶体液输注'),token('a_insulin','Begin the prescribed IV insulin with electrolyte monitoring','开始医嘱的静脉胰岛素并监测电解质'),token('a_bicarb','Request bicarbonate now to normalize pH rapidly','立即申请碳酸氢盐以迅速使 pH 正常'),token('a_delay','Delay metabolic treatment until nausea resolves and oral intake resumes','待恶心消退、恢复口服进食后再开始代谢治疗')],'correct':['a_fluid','a_insulin']},'parameters':{'prompt':pair('Track resolution of ketoacidosis','追踪酮症酸中毒消退'),'tokens':[token('p_ketone','Blood β-hydroxybutyrate','血 β-羟丁酸'),token('p_ph','Venous pH','静脉血 pH'),token('p_inr','INR','国际标准化比值（INR）'),token('p_tsh','Thyroid-stimulating hormone','促甲状腺激素')],'correct':['p_ketone','p_ph']}};Q.append(q)
E.append({'id':q['id'],'sourceIds':['dka-consensus'],'proposition':'Differentiate DKA using confirming labs; fluids+insulin; track blood ketones and pH.','differentialDefense':'Diabetes/dehydration overlaps DKA and HHS; five-day poor intake makes starvation ketosis plausible before laboratory synthesis. Marked hyperglycemia/ketonemia/acidosis resolve the differential.','parameterDefense':'INR/TSH are orthogonal to ketoacidosis resolution; potassium remains monitored for safety but is not offered as a wrong resolution parameter.','reviewAttention':'Independent reviewer must affirm all three conditions compete and the action distractors meet the semantic floor; numeric values are fictional, protocol thresholds are sourced.'})

q=question(1,6,'highlight','Reduction of Risk Potential','Intrapartum Fetal Monitoring','recognize_cues',
 ('A term client is receiving oxytocin during labor. The unit protocol requires stopping oxytocin and starting intrauterine resuscitation when excessive contractions occur with recurrent late decelerations. It defines excessive contractions as more than five in10minutes, averaged over30minutes. Highlight the findings that together meet this trigger.','一名足月产妇在分娩过程中接受缩宫素输注。科室规程规定，若宫缩过频并伴反复晚期减速，应停止缩宫素并开始宫内复苏。宫缩过频定义为：以 30 分钟为观察窗口，平均每 10 分钟超过 5 次宫缩。标出共同满足这一触发条件的表现。'),
 ('Six contractions per10minutes across30minutes meets the stated frequency threshold. Gradual decelerations that begin after contractions start, reach their lowest point after the contraction peak and recover after contractions end describe late decelerations. Their recurrence with the excessive contractions triggers the protocol.','连续 30 分钟内平均每 10 分钟 6 次宫缩，达到题干规定的频率标准。胎心率逐渐下降，始于宫缩开始之后，最低点晚于宫缩高峰，宫缩结束后才恢复，描述的是晚期减速。此类减速反复出现且伴宫缩过频，符合规程的处理条件。'),
 ('Assess contraction frequency and the timing of fetal slowing together.','结合宫缩频率与胎心减慢相对宫缩的时相关系进行判断。'),
 [term('late deceleration','晚期减速','胎心率减速的时相滞后于宫缩。'),term('tachysystole','宫缩过频','按规定观察窗口计算的宫缩频率过高。')],
 [reason('s1','A baseline of145/min is within the usual110–160/min range and does not supply either trigger.','胎心基线 145 次/分位于常用的 110–160 次/分范围，不构成题干所列触发条件。'),reason('s2','Moderate variability is a reassuring feature, although it does not cancel the need to respond to recurrent late decelerations with excessive contractions.','中等变异通常提示胎儿状况较好，但不能抵消对宫缩过频伴反复晚期减速进行处理的需要。'),reason('s3','Six contractions per10minutes across the30-minute window exceeds the explicit limit.','在 30 分钟窗口内平均每 10 分钟 6 次宫缩，超过了题干规定的频率上限。'),reason('s4','The delayed timing on most contractions identifies recurrent late decelerations.','多数宫缩伴随这种滞后的减速时相，提示反复晚期减速。'),reason('s5','Accelerations with movement are not late decelerations and do not establish excessive contraction frequency.','胎动时出现的加速不是晚期减速，也不能证明宫缩过频。')])
q['highlight']={'segments':[token('intro','Continuous monitoring note:','持续监护记录：'),*[{**token(*x),'selectable':True} for x in [('s1','Fetal heart rate baseline is145/min.','胎心率基线为 145 次/分。'),('s2','Baseline variability is moderate.','基线变异为中等。'),('s3','There are six contractions in each of the last three10-minute intervals.','最近连续三个 10 分钟时段中，每个时段均有 6 次宫缩。'),('s4','With most contractions, gradual fetal slowing begins after the contraction starts, reaches its nadir after the contraction peak, and returns to baseline after the contraction ends.','多数宫缩时，胎心率在宫缩开始后逐渐减慢，最低点出现在宫缩高峰之后，宫缩结束后才恢复至基线。'),('s5','Two accelerations occur with fetal movement.','胎动时出现两次胎心加速。')]]],'correct':['s3','s4']};Q.append(q)
E.append({'id':q['id'],'sourceIds':['acog-fhr','nice-fhr'],'proposition':'Apply a conjunctive excessive-contractions/recurrent-late-decelerations trigger.','protocolBoundary':'Explicit US-style >5/10min averaged30min definition; do not substitute NICE’s differently worded frequency definition.','formatDefense':'Two of five findings; moderate variability/accelerations do not erase the triggered action. No tracing or visual is fabricated.'})
save(1,Q,E)
