from raw_common import *
Q=[];E=[]
q=question(3,1,'fill_in_blank','Safety and Infection Prevention and Control','PPE & Sterile Technique','take_action',
 ('After completing care, a nurse removes and discards gloves and the remaining PPE using the facility procedure. What infection-prevention practice involving the nurse’s hands is required immediately after all PPE is removed? Enter the name of the practice.','完成护理后，护士按机构规程脱下并丢弃手套及其余个人防护用品（PPE）。所有 PPE 脱除后，应立即对双手采取哪项感染预防措施？填写该措施名称。'),
 ('Perform hand hygiene immediately after PPE removal. Gloves can have unnoticed defects, and the hands may become contaminated during removal. Wearing gloves does not replace hand hygiene.','脱除 PPE 后应立即进行手卫生。手套可能存在未被发现的破损，脱除时双手也可能受到污染。戴手套不能替代手卫生。'),
 ('Remember the protection needed after the barrier has been removed.','想到防护屏障移除后仍需采取的保护措施。'),
 [term('hand hygiene','手卫生','通过适当洗手或手消毒减少手部微生物的措施。'),term('PPE','个人防护用品','用于减少接触危害的防护装备。')],
 [reason('practice','Hand hygiene reduces contamination that may remain after glove and PPE removal; putting on another pair of gloves alone is insufficient.','手卫生可减少脱除手套及 PPE 后可能残留的污染；仅换戴另一副手套并不充分。')],difficulty='easy')
q['blanks']=[{'id':'practice','prompt':pair('Required practice','必须采取的措施'),'acceptable':['hand hygiene','handwashing','hand washing','wash hands','hand cleaning','手卫生','洗手']}];Q.append(q)
E.append({'id':q['id'],'sourceIds':['cdc-hand-hygiene'],'proposition':'Perform hand hygiene immediately after PPE removal.','formatDefense':'Finite short-answer vocabulary addresses the explicit census topic×format request. Soap-and-water variants are accepted; no claim that one product is universal.'})

q=question(3,2,'fill_in_blank','Pharmacological and Parenteral Therapies','IV Fluid Calculations','take_action',
 ('An adult has an order for500 mL of0.9% sodium chloride over3 hours20 minutes by gravity infusion. The administration set delivers20 gtt/mL. Calculate the total infusion time in minutes and the rate in gtt/min. Round the drip rate to a whole number.','一名成人的医嘱为：通过重力输液，在 3 小时 20 分钟内输入 500 mL 的 0.9% 氯化钠。输液器滴系数为 20 gtt/mL。计算总输注时间（分钟）及滴速（gtt/min）。滴速取整数。'),
 ('The interval is3 ×60 +20 =200 minutes. The drip rate is500 ×20 ÷200 =50 gtt/min. Using3.20 hours would misrepresent the20-minute portion.','输注时长为 3 × 60 + 20 = 200 分钟。滴速为 500 × 20 ÷ 200 = 50 gtt/min。把时长写成 3.20 小时会错误换算其中的 20 分钟。'),
 ('Keep minutes in the denominator when the desired result is drops per minute.','结果要求每分钟滴数时，分母中的时间应统一为分钟。'),
 [term('drop factor','滴系数','输液器每毫升液体形成的滴数。'),term('gravity infusion','重力输液','利用高度差使液体经输液器进入患者体内。')],
 [reason('minutes','Convert all three hours to180 minutes before adding20 minutes.','先将三小时换算为 180 分钟，再加上 20 分钟。'),reason('drip','Multiply500 mL by20 gtt/mL, then divide by200 minutes; the mL units cancel.','用 500 mL 乘以 20 gtt/mL，再除以 200 分钟；mL 单位相消。')])
q['blanks']=[{'id':'minutes','prompt':pair('Total minutes','总分钟数'),'numeric':{'value':200,'tolerance':0,'unit':'min'}},{'id':'drip','prompt':pair('Rate in gtt/min','滴速，gtt/min'),'numeric':{'value':50,'tolerance':0,'unit':'gtt/min'}}];Q.append(q)
E.append({'id':q['id'],'sourceIds':['arithmetic'],'proposition':'500mL×20gtt/mL÷200min=50gtt/min.','fictionalInputs':'Prescribed amount, interval and supplied set factor; no clinical fluid-dose recommendation.'})

q=question(3,3,'dropdown_cloze','Psychosocial Integrity','Electroconvulsive Therapy (ECT)','generate_solutions',
 ('Before an ECT course, a client asks whether memory changes always disappear as soon as anesthesia wears off. Complete the nurse’s response with accurate counseling about memory effects and follow-up.','开始一个疗程的电休克治疗（ECT）前，患者询问：记忆变化是否总会在麻醉作用消退后立即消失？选择准确描述记忆影响和随访方式的内容，补全护士的回答。'),
 ('ECT can affect memory, including gaps for events around treatment that may persist in some people. The team should assess memory and cognition during the course and discuss changes with the client. Neither guaranteed immediate recovery nor inevitable permanent loss of all memory is accurate.','ECT 可影响记忆，部分患者对治疗前后事件的记忆缺失可能持续存在。团队应在疗程中评估记忆和认知，并与患者讨论变化。保证立即恢复，或断言所有记忆必然永久丧失，都不准确。'),
 ('Avoid absolute promises; connect a variable treatment effect with a concrete monitoring plan.','避免绝对保证；把可能因人而异的治疗影响与具体监测安排联系起来。'),
 [term('memory gap','记忆缺失','无法回忆某段经历或事件。'),term('cognition','认知','包括注意、记忆和理解等思维能力。')],
 [reason('effect','Some memory gaps can persist. Anesthesia ending does not guarantee all memory effects end; universal loss of all past memories is also false.','部分记忆缺失可能持续。麻醉结束并不保证所有记忆影响都结束；所有既往记忆都会丧失的说法也不正确。'),reason('followup','Discuss and assess changes during treatment. Waiting until the entire course ends can delay reassessment, while dismissing every concern as depression overlooks possible treatment effects.','应在治疗过程中讨论并评估变化。等全部疗程结束再处理可能延误复评；把每项担忧都归因于抑郁则可能忽视治疗相关影响。')])
q['clozeStem']=pair('“{{effect}}. We will {{followup}}.”','“{{effect}}。我们会 {{followup}}。”')
q['dropdowns']=[{'id':'effect','options':[token('variable','Some memory gaps can last beyond the immediate recovery period','部分记忆缺失可持续到即时恢复期之后'),token('instant','Every memory effect ends when the anesthetic wears off','麻醉作用一消退，所有记忆影响都会结束'),token('all','Everyone permanently loses all memories from before treatment','每个人都会永久丧失治疗前的所有记忆')],'correct':'variable'},{'id':'followup','options':[token('monitor','assess memory during the course and discuss any changes you notice','在疗程中评估记忆，并讨论您注意到的任何变化'),token('wait','wait until every session is finished before discussing memory','等整个疗程结束后才讨论记忆问题'),token('dismiss','assume all memory concerns are caused only by depression','认定所有记忆担忧都只是抑郁所致')],'correct':'monitor'}];Q.append(q)
E.append({'id':q['id'],'sourceIds':['ect-side-effects','ect-recovery'],'proposition':'Memory effects vary and some gaps persist; assess during the course.','clinicalBoundary':'No quantitative incidence, universal permanence or guaranteed recovery time.','formatDefense':'Two independent counseling dimensions, with explicit reasoning for each offered misconception.'})

q=question(3,4,'highlight','Health Promotion and Maintenance','Reproductive & Endocrine Health','analyze_cues',
 ('A client wishes to rely on the lactational amenorrhea method for contraception. The clinic requires all three conditions: less than6 months postpartum, no return of menstrual periods, and fully or nearly fully breastfeeding with feeding intervals no longer than4 hours by day or6 hours at night. Highlight the history findings that prevent relying on this method now.','患者希望依靠哺乳闭经法避孕。诊所要求同时满足三个条件：产后不足 6 个月；尚未恢复月经；完全或接近完全母乳喂养，白天喂养间隔不超过 4 小时、夜间不超过 6 小时。标出目前不符合这一方法使用条件的病史表现。'),
 ('A true menstrual period has returned, and the eight-hour overnight feeding gap exceeds the stated limit. Either finding means the stated method criteria are not all met. Being four months postpartum and breastfeeding frequently by day do not correct those gaps.','已经恢复一次真正月经，且夜间八小时不喂养超过了规定间隔。任一表现都意味着未同时满足这一方法的使用条件。产后四个月及白天频繁母乳喂养，不能弥补这两项不符合条件的情况。'),
 ('For a method requiring every condition, check each criterion separately rather than averaging favorable and unfavorable findings.','对要求全部条件同时成立的方法，应逐项核对，不能用有利表现抵消不符合条件的表现。'),
 [term('amenorrhea','闭经','没有月经来潮。'),term('lactation','泌乳与哺乳','乳汁产生及用于喂养婴儿的过程。')],
 [reason('s1','Four months postpartum meets the under-six-month criterion.','产后四个月符合不足六个月的条件。'),reason('s2','The confirmed return of menses means amenorrhea is no longer present.','确认月经恢复，说明闭经条件已不再成立。'),reason('s3','A two-to-three-hour daytime interval meets the stated daytime limit.','白天每两至三小时喂养一次，符合题干规定的白天间隔。'),reason('s4','An eight-hour interval without breastfeeding or pumping exceeds the stated nighttime limit.','八小时既不亲喂也不泵奶，超过了规定的夜间间隔。'),reason('s5','Wanting to avoid pregnancy explains the need for contraception but is not a biological exclusion criterion.','希望避免怀孕说明需要避孕，但其本身不是生理性不适用条件。')])
q['highlight']={'segments':[token('intro','Contraceptive interview:','避孕访谈：'),*[{**token(*x),'selectable':True} for x in [('s1','The infant is four months old.','婴儿四个月大。'),('s2','A normal menstrual period returned last week; postpartum bleeding had ended months earlier.','上周恢复了一次正常月经；产后恶露已在数月前结束。'),('s3','The client breastfeeds every two to three hours during the day.','患者白天每两至三小时亲喂一次。'),('s4','The infant sleeps eight hours at night, and the client neither breastfeeds nor pumps during that interval.','婴儿夜间连续睡八小时，患者期间既不亲喂也不泵奶。'),('s5','The client wishes to avoid another pregnancy for at least two years.','患者希望至少两年内不再怀孕。')]]],'correct':['s2','s4']};Q.append(q)
E.append({'id':q['id'],'sourceIds':['cdc-lam'],'proposition':'Returned menses and excessive night interval each break explicit LAM conditions.','formatDefense':'Two of five; postpartum age and daytime feeding are genuine favorable near-misses. Distinguishes menses from lochia.'})

q=question(3,5,'fill_in_blank','Reduction of Risk Potential','ABG & Acid-Base Interpretation','analyze_cues',
 ('An adult with reduced ventilation has an arterial pH of7.28, PaCO₂60 mmHg and HCO₃⁻27 mEq/L. The laboratory reference intervals are pH7.35–7.45, PaCO₂35–45 mmHg and HCO₃⁻22–26 mEq/L. Name the primary acid-base disorder, without adding a compensation classification.','一名通气减少的成人，动脉血 pH 为 7.28、PaCO₂ 为 60 mmHg、HCO₃⁻ 为 27 mEq/L。实验室参考范围为 pH 7.35–7.45、PaCO₂ 35–45 mmHg、HCO₃⁻ 22–26 mEq/L。填写主要酸碱紊乱名称，无需填写代偿分类。'),
 ('The pH indicates acidemia. Elevated PaCO₂ explains the acidifying change, so the primary disorder is respiratory acidosis. Bicarbonate is slightly elevated rather than decreased and is not the cause of this primary acidemia.','pH 提示酸血症。PaCO₂ 升高解释了酸化变化，因此主要紊乱为呼吸性酸中毒。碳酸氢根轻度升高而非降低，并不是本次原发性酸血症的原因。'),
 ('Identify the pH direction, then match the component that explains it.','先判断 pH 的方向，再匹配能解释这一方向的成分。'),
 [term('respiratory acidosis','呼吸性酸中毒','二氧化碳潴留导致的原发性酸化过程。'),term('ventilation','通气','空气进出肺泡、参与二氧化碳排出的过程。')],
 [reason('disorder','Respiratory acidosis fits low pH with high PaCO₂. Metabolic acidosis would require a primary bicarbonate deficit; alkalosis does not fit this acidifying CO₂ pattern.','低 pH 合并高 PaCO₂ 符合呼吸性酸中毒。原发性代谢性酸中毒应有碳酸氢根不足；碱中毒不符合本题二氧化碳导致酸化的模式。')])
q['blanks']=[{'id':'disorder','prompt':pair('Primary disorder','主要紊乱'),'acceptable':['respiratory acidosis','呼吸性酸中毒']}];Q.append(q)
E.append({'id':q['id'],'sourceIds':['abg-ranges'],'proposition':'Acidemia driven by high PaCO2; respiratory acidosis.','physiologyCheck':'6.1+log10(27/(0.03*60))≈7.28. Compensation label deliberately outside asked construct.','formatDefense':'Finite diagnostic term, no free-form rationale to grade.'})

q=question(3,6,'fill_in_blank','Physiological Adaptation','Diabetic Ketoacidosis (DKA)','analyze_cues',
 ('An adult with type2 diabetes taking an SGLT2 inhibitor develops nausea and deep rapid breathing after markedly reduced food intake. Glucose is176 mg/dL, blood β-hydroxybutyrate4.5 mmol/L, venous pH7.24 and bicarbonate13 mEq/L. The emergency team is treating the metabolic crisis. Its diagnostic pathway recognizes DKA in a person with diabetes when ketones are at least3.0 mmol/L and pH is below7.3 or bicarbonate below18 mEq/L; marked hyperglycemia is not required. For subtype classification, it distinguishes glucose below200 mg/dL from higher glucose. What glucose-defined subtype of DKA is present?','一名服用 SGLT2 抑制剂的 2 型糖尿病成人，在进食明显减少后出现恶心及深快呼吸。血糖 176 mg/dL，血 β-羟丁酸 4.5 mmol/L，静脉血 pH 7.24，碳酸氢根 13 mEq/L。急诊团队正在处理这一代谢危象。其诊断路径规定：糖尿病患者血酮至少 3.0 mmol/L，且 pH 低于 7.3 或碳酸氢根低于 18 mEq/L 时可诊断 DKA，并不要求明显高血糖。划分亚型时，该路径将血糖低于 200 mg/dL 的情况与更高血糖区分。这属于按血糖特点划分的哪一种 DKA 亚型？'),
 ('This is euglycemic DKA: ketoacidosis with glucose below200 mg/dL. Diabetes, significant ketonemia and metabolic acidosis are present despite the absence of marked hyperglycemia. Reduced intake and SGLT2 inhibitor use are relevant clinical clues; the glucose value does not make the acidosis benign.','这是正常血糖性 DKA，即血糖低于 200 mg/dL 的酮症酸中毒。患者有糖尿病、明显酮血症及代谢性酸中毒，虽未出现明显高血糖仍符合诊断。摄入减少及 SGLT2 抑制剂使用是相关临床线索；这一血糖数值并不意味着酸中毒无害。'),
 ('Integrate blood ketones and acid-base results instead of using glucose alone to exclude a metabolic emergency.','结合血酮和酸碱结果，不要仅凭血糖排除代谢急症。'),
 [term('euglycemic DKA','正常血糖性糖尿病酮症酸中毒','血糖未明显升高仍发生的糖尿病酮症酸中毒；名称并不表示整体代谢正常。'),term('SGLT2 inhibitor','SGLT2 抑制剂','通过增加尿糖排泄降低血糖的一类药物。')],
 [reason('subtype','Euglycemic DKA names the subtype with glucose below200 mg/dL. The ketone and acidosis findings exclude interpreting this as uncomplicated mild glucose elevation.','正常血糖性 DKA 指血糖低于 200 mg/dL 的这一亚型。酮血症和酸中毒结果不支持将其仅解释为无并发症的轻度血糖升高。')],difficulty='hard')
q['blanks']=[{'id':'subtype','prompt':pair('DKA subtype','DKA 亚型'),'acceptable':['euglycemic diabetic ketoacidosis','euglycaemic diabetic ketoacidosis','euglycemic DKA','euglycaemic DKA','euglycemic','euglycaemic','euDKA','EDKA','正常血糖性糖尿病酮症酸中毒','正常血糖性DKA','正常血糖性 DKA','正常血糖性']}];Q.append(q)
E.append({'id':q['id'],'sourceIds':['dka-consensus'],'proposition':'Recognize euglycemic DKA despite glucose176mg/dL in diabetes with ketonemia/acidosis.','clinicalBoundary':'Sourced diagnostic criteria; explicit treatment underway, no drug-stop/dosing instruction. Euglycemic threshold<200mg/dL is a source-owned subtype definition, not a claim that176 is normal fasting glucose.','formatDefense':'Finite named subtype with US/UK spelling, abbreviation and Chinese equivalents.'})
save(3,Q,E)
