from edit import *
q=load(25);bi(q['caseStudy']['title'],'Parenteral nutrition after prolonged poor intake','长期摄入不足后开始肠外营养');p=part(q,'q2')
bi(p['stem'],'At Stage 1, interpret the electrolyte shift and the concurrent glucose elevation after nutrition is started.','在阶段 1，解释开始营养后电解质转移及同时出现的血糖升高。');bi(p['clozeStem'],'The simultaneous electrolyte decline is consistent with the refeeding process. PN carbohydrate delivery has likely caused {{d2}}. The glucose elevation is best interpreted as {{d3}}.','电解质同时下降符合再喂养过程。PN 的碳水化合物供给很可能导致 {{d2}}。血糖升高最好理解为 {{d3}}。');p['dropdowns']=[d for d in p['dropdowns'] if d['id']!='d1'];p['rationale']['byChoice']=[v for v in p['rationale']['byChoice'] if v['refId']!='d1'];anchor(p,'stage_1')
c=content(q,1);rep(c,'en','The dressing was changed 24 hours ago per protocol.','The current dressing was applied when the PICC was placed 12 hours earlier.');rep(c,'zh','敷料 24 小时前已按规程更换。','当前敷料是在 12 小时前置入 PICC 时贴上的。')
p=part(q,'q3');rep(p['rationale']['correct'],'en','The PICC site must be cultured and treated, but it does not explain the established electrolyte triad or current rhythm instability.','The electrolyte decline strongly supports urgent monitored correction. Infection may coexist or contribute to the deterioration; the PICC findings and fever require timely parallel evaluation and treatment.');rep(p['rationale']['correct'],'zh','PICC 处需要培养和治疗，但不能解释已形成的电解质三联下降或当前心律不稳。','电解质下降强烈支持在监测下紧急纠正。感染可同时存在或促成恶化；PICC 发现和发热需要及时并行评估及治疗。');bi(obj(p['rationale']['byChoice'],'q3_B','refId'),'The PICC findings and fever require prompt infection assessment and prescribed treatment alongside urgent electrolyte correction; infection cannot be excluded as a contributor to deterioration.','PICC 发现与发热需要及时评估感染并按医嘱治疗，同时紧急纠正电解质；不能排除感染促成病情恶化。');anchor(p,'stage_2')
p=part(q,'q4');bi(obj(p['options'],'q4_D'),'Obtain ordered blood cultures from the PICC and a peripheral site promptly, ideally before the first ordered vancomycin dose, without materially delaying antibiotic treatment.','及时按医嘱从 PICC 和外周抽取血培养，最好在首次医嘱万古霉素前完成，但不能实质性延误抗生素治疗。');bi(obj(p['rationale']['byChoice'],'q4_D','refId'),'Prompt cultures improve organism identification. Collect before antibiotics when feasible without material delay; escalate collection difficulties while preserving timely prescribed treatment.','及时培养有助于识别病原体。应在可行且不实质性延误治疗时于抗生素前采集；采集困难应升级处理，同时确保及时按医嘱治疗。');rep(p['rationale']['correct'],'en','obtain paired cultures before vancomycin.','obtain paired cultures promptly, ideally before vancomycin without materially delaying treatment.');rep(p['rationale']['correct'],'zh','并在 vancomycin 前抽取配对血培养。','并及时抽取配对血培养，最好在万古霉素前完成且不实质性延误治疗。');anchor(p,'stage_2')
p=part(q,'q5');bi(p['stem'],'Using the Stage 2 findings, consider the proposed orders shown in the rows. If prescribed, which implementation category best describes each action?','根据阶段 2 发现，考虑各行所列的拟议医嘱。如果这些医嘱被开立，每项措施最符合哪一种执行类别？')
bi(obj(p['matrix']['columns'],'q5_c1'),'Immediate nutrition/electrolyte intervention alongside infection evaluation','与感染评估并行的立即营养/电解质干预');bi(obj(p['matrix']['columns'],'q5_c2'),'Prompt diagnostic sampling, ideally before antibiotics without material delay','及时诊断采样，最好在抗生素前且不实质性延误治疗');bi(obj(p['matrix']['columns'],'q5_c3'),'Prompt antimicrobial treatment; culture collection must not materially delay it','及时抗菌治疗；采集培养不能实质性延误治疗')
bi(p['rationale']['correct'],'TPN rate reduction and electrolyte repletion address the immediate metabolic and rhythm risk while infection is evaluated in parallel. Obtain paired cultures promptly, ideally before vancomycin, but preserve timely antibiotic treatment if collection is delayed. Glucose monitoring and insulin coverage continue alongside these urgent interventions.','降低 TPN 速率及补充电解质处理当前代谢和心律风险，同时并行评估感染。应及时抽取配对血培养，最好在万古霉素前完成，但如采集延误仍须确保及时使用抗生素。血糖监测及胰岛素覆盖与这些紧急措施并行继续。');bi(obj(p['rationale']['byChoice'],'q5_r3','refId'),'This is diagnostic sampling: obtain cultures as soon as possible and preferably before antibiotics without materially delaying treatment.','这是诊断采样：应尽快抽取培养，最好在抗生素前完成，但不能实质性延误治疗。');bi(obj(p['rationale']['byChoice'],'q5_r4','refId'),'This is antimicrobial treatment: begin promptly after cultures when they can be obtained promptly; difficulty collecting cultures must not materially delay the antibiotic.','这是抗菌治疗：若能及时采集，抽取培养后即应及时给药；采集困难不能实质性延误抗生素。');bi(p['testTakingStrategy'],'Distinguish each action’s purpose and urgency. Diagnostic sampling and antimicrobial treatment should be coordinated, with neither neglected during urgent metabolic stabilization.','区分各措施的目的和紧迫性。诊断采样与抗菌治疗应协调进行，在紧急稳定代谢状态时两者都不能忽视。');anchor(p,'stage_2');save(q)
