from edit import *
q=load(32);s=q['caseStudy']['summary'];rep(s,'en','The case follows alteplase eligibility screening, thrombectomy preparation, and post-reperfusion deterioration.','The stroke team is evaluating the acute neurologic change and treatment options.');rep(s,'zh','本病例追踪 alteplase 适用性筛查、血栓取出术准备，以及再灌注后病情恶化。','卒中团队正在评估急性神经变化及治疗选择。');c=content(q,0);old=pair('The neurologist states the client is not a candidate for IV alteplase because of the INR and orders CTA head and neck to evaluate for large-vessel occlusion and potential mechanical thrombectomy. ','神经科医生说明患者因 INR 不符合 IV alteplase 条件，并医嘱行头颈 CTA，以评估是否有大血管闭塞及机械取栓可能性。')
for lang in ['en','zh']:rep(c,lang,old[lang],'')
c=content(q,1)
for lang in ['en','zh']:c[lang]=old[lang]+c[lang]
rep(c,'en','Wife holds durable power of attorney and provides consent because the client cannot provide informed consent due to aphasia.','The clinician assesses this specific urgent decision using supported communication, including short statements, pictures and verified yes/no responses. Despite support, the client cannot demonstrate understanding of the procedure’s material benefits and risks or communicate a consistent choice. The wife is the verified healthcare agent under his durable power of attorney and is available for the consent discussion.');rep(c,'zh','由于失语导致患者无法知情同意，持有医疗持久授权的妻子代为同意。','临床医师采用简短陈述、图片和经核实的是/否回应等支持性沟通方式，评估患者对这项紧急决策的能力。虽提供支持，患者仍无法展示对操作主要收益与风险的理解，亦无法传达一致选择。妻子为经核实、由医疗持久授权文件指定的医疗代理人，可参与同意讨论。')
old=pair('After 20 minutes, BP is 168/94 mmHg. Client remains NPO. Two patent IV lines are in place. Continuous cardiac monitoring is active and the stroke flow sheet is current.','20 分钟后 BP 为 168/94 mmHg。患者继续 NPO。已有两条通畅静脉通路。持续心电监护已连接，卒中流程记录已更新。')
for lang in ['en','zh']:rep(c,lang,old[lang],pair('Dysphagia screening is pending. Preparation and treatment under these orders are about to begin.','吞咽筛查仍待完成。即将根据这些医嘱开始准备及治疗。')[lang])
c=content(q,2)
for lang in ['en','zh']:c[lang]=pair('Before transfer, the prescribed nicardipine infusion was started. ','转运前已开始医嘱尼卡地平输注。')[lang]+old[lang]+pair(' Proxy consent was verified before the procedure.\n\n',' 操作前已核实代理人同意。\n\n')[lang]+c[lang]
anchor(part(q,'q2'),'stage_1');p=part(q,'q4');bi(p['stem'],'At Stage 2, review the current orders and assessments. Which nursing actions are appropriate before transfer for the planned procedure? Select all that apply.','在阶段 2，请查看当前医嘱与评估。为计划的操作转运前，哪些护理措施合适？选择所有适用项。');bi(obj(p['options'],'D'),'Verify the assessed decision-specific incapacity despite supported communication and consent from the verified healthcare agent under the facility process.','按机构流程核实：经支持性沟通后评估确认患者缺乏此项决策能力，并已取得经核实的医疗代理人同意。');rep(p['rationale']['correct'],'en','confirms proxy consent when the neurologic deficit prevents informed consent.','confirms authorized proxy consent after decision-specific incapacity is assessed despite supported communication. Aphasia alone does not establish incapacity.');rep(p['rationale']['correct'],'zh','并在神经缺损妨碍知情同意时确认代理人同意。','并在提供支持性沟通后，经评估确认患者缺乏此项决策能力时核实授权代理人同意。失语本身并不等于无决策能力。');bi(obj(p['rationale']['byChoice'],'D','refId'),'The basis for proxy involvement is the documented assessment of this decision after communication support and the verified healthcare-agent authority. Do not infer incapacity solely from aphasia.','代理人参与的依据是支持性沟通后对此项决策的评估记录，以及已核实的医疗代理权限。不能仅因失语推断患者无决策能力。');anchor(p,'stage_2');save(q)
q=load(33);c=content(q,1);begin=c['en'].index(' The belt,');end=c['en'].index(' During the sweep,');c['en']=c['en'][:begin]+' The room contains a leather belt, phone charger cord, razor, and plastic bag. The bathroom door can lock from inside. IV tubing and a pulse-oximetry cable are required for ongoing antibiotics and oxygenation monitoring; their loose lengths require review under the approved clinical and device safety procedures. The IV pole and overbed table are required for treatment and meals; assessment finds no loose or detachable parts readily usable for self-harm in this setting.'+c['en'][end:]
begin=c['zh'].index('在告知患者后');end=c['zh'].index('清理房间期间');c['zh']=c['zh'][:begin]+'房内有皮带、手机充电线、剃刀和塑料袋。浴室门可从内部上锁。持续抗生素治疗和氧合监测需要静脉输液管及脉搏血氧导线；松散的管线长度需按经批准的临床与设备安全流程评估。输液架和床旁餐桌为治疗及进餐所需；评估未发现可在此情境下轻易用于自伤的松散或可拆卸部件。'+c['zh'][end:]
p=part(q,'q3');bi(obj(p['rationale']['byChoice'],'r5','refId'),'Continue medically necessary treatment while reducing tubing and cable risk through approved clinical and device procedures and continuous qualified observation. Do not improvise cutting or alteration of equipment at the bedside.','应继续必要治疗，按经批准的临床及设备流程降低管线风险，并由合格人员持续观察。不可在床旁自行剪切或改装设备。');anchor(p,'stage2');save(q)
