/**
 * Campaign 16 Phase B, Stage 1 iteration 1.
 *
 * Patches only the nine frozen Stage 2 BLOCK rows already present under
 * unpublished `_r2` IDs. No row is rematerialized and no ID is minted.
 */
import { replaceText, runPatch, setValue } from "../patch-raw";

export const ops = [
  setValue({
    id: "gpt_balance3_2026_07_16_dc_discharge_planning_handoff_08_r2",
    path: ["dropdowns", { id: "d2" }, "options", { id: "o2" }, "en"],
    before: "the date of the last injection",
    after: "the date of the next treatment-plan review",
    note: "Replace the d1-redundant last-injection date with a plausible receiving-program date that does not determine medication continuity.",
  }),
  setValue({
    id: "gpt_balance3_2026_07_16_dc_discharge_planning_handoff_08_r2",
    path: ["dropdowns", { id: "d2" }, "options", { id: "o2" }, "zh"],
    before: "末次注射日期",
    after: "下次治疗计划复审日期",
    note: "Chinese parity for the repaired d2/o2 distractor.",
  }),

  setValue({
    id: "gpt_balance3_2026_07_16_hl_disaster_emergency_preparedness_13_r2",
    path: ["rationale", "correct", "en"],
    before: "The safe response follows the downtime plan stated in the case: use controlled paper records, verify identity without barcode scanning, read back critical results, document medications as they are given, and reconcile before retrospective entry. Personal texting and memory-based reconstruction create privacy and medication-safety risks.",
    after: "Safe downtime care uses controlled paper records, verifies identity without barcode scanning, reads back critical results, documents medications as they are given, and reconciles records before retrospective entry. Personal texting and memory-based reconstruction create privacy and medication-safety risks.",
    note: "Remove the false claim that the deleted action recital remains stated in the case.",
  }),
  setValue({
    id: "gpt_balance3_2026_07_16_hl_disaster_emergency_preparedness_13_r2",
    path: ["rationale", "correct", "zh"],
    before: "安全应对必须遵循题干给出的停机计划：使用受控纸质记录，在无法扫码时核对两项身份，复诵危急结果，给药时实时记录，并在事后补录前完成核对。使用私人短信和凭记忆重建记录会造成隐私及用药安全风险。",
    after: "安全的停机护理应使用受控纸质记录，在无法扫码时核对患者身份，复诵危急结果，给药时实时记录，并在事后补录前完成记录核对。使用私人短信和凭记忆重建记录会造成隐私及用药安全风险。",
    note: "Chinese parity for removal of the false stem-reference claim.",
  }),
  setValue({
    id: "gpt_balance3_2026_07_16_hl_disaster_emergency_preparedness_13_r2",
    path: ["testTakingStrategy", "en"],
    before: "Use every operational control explicitly named in the activated plan and reject shortcuts that lose traceability.",
    after: "Evaluate each action for traceability, patient identification, closed-loop communication, and contemporaneous medication documentation; reject insecure or memory-based shortcuts.",
    note: "Replace the misleading select-everything instruction with discriminating criteria.",
  }),
  setValue({
    id: "gpt_balance3_2026_07_16_hl_disaster_emergency_preparedness_13_r2",
    path: ["testTakingStrategy", "zh"],
    before: "使用启动计划中明确列出的每项操作控制，排除会失去可追溯性的捷径。",
    after: "根据可追溯性、患者身份核对、闭环沟通和给药时同步记录来评估每项行动；排除不安全或依赖记忆的捷径。",
    note: "Chinese parity for the discriminating strategy repair.",
  }),

  setValue({
    id: "gpt_mocsic_2026_07_15_dc_disaster_emergency_preparedness_18_r2",
    path: ["rationale", "correct", "en"],
    before: "Before an authenticated all-clear, the unit follows secure-in-place actions and does not open the door for an unverified voice. After the all-clear, staff transition to clinical triage in the designated safe area; resuming routine operations would skip the plan's post-event response.",
    after: "Before an authenticated all-clear, the unit remains secured and does not open the door for an unverified voice. After the all-clear, staff should follow authenticated instructions and render clinical aid when safe; resuming routine operations without following those instructions skips the post-event response.",
    note: "Replace the unsupported designated-area triage sequence with current CISA-supported post-event behavior.",
  }),
  setValue({
    id: "gpt_mocsic_2026_07_15_dc_disaster_emergency_preparedness_18_r2",
    path: ["rationale", "correct", "zh"],
    before: "在收到经验证的解除警报前，病区应执行就地防护措施，不因未经核实的声音而开门。解除警报后，工作人员转入指定安全区域开展临床分诊；直接恢复常规运行会跳过计划规定的事件后应对。",
    after: "在收到经验证的解除警报前，病区应保持锁闭，不因未经核实的声音而开门。解除警报后，工作人员应遵循经验证的指示，并在确保安全时提供临床救助；不遵循这些指示就直接恢复常规运行会跳过事件后应对。",
    note: "Chinese parity for the sourced post-event action repair.",
  }),
  setValue({
    id: "gpt_mocsic_2026_07_15_dc_disaster_emergency_preparedness_18_r2",
    path: ["rationale", "byChoice", { refId: "1" }, "en"],
    before: "The plan explicitly requires secure-in-place behavior before the all-clear.",
    after: "Remaining secured and refusing an unverified request to open the door protects the unit before the all-clear.",
    note: "Remove the unsupported assertion about what an unsupplied plan explicitly requires.",
  }),
  setValue({
    id: "gpt_mocsic_2026_07_15_dc_disaster_emergency_preparedness_18_r2",
    path: ["rationale", "byChoice", { refId: "1" }, "zh"],
    before: "计划明确要求在解除警报前就地防护。",
    after: "在解除警报前保持锁闭并拒绝未经核实的开门请求，可保护病区安全。",
    note: "Chinese parity for removal of the unsupported plan assertion.",
  }),
  setValue({
    id: "gpt_mocsic_2026_07_15_dc_disaster_emergency_preparedness_18_r2",
    path: ["rationale", "byChoice", { refId: "2" }, "en"],
    before: "The plan directs clinical triage only after the authenticated all-clear.",
    after: "After the authenticated all-clear, staff should follow the issued instructions and render clinical aid when safe.",
    note: "Bind the keyed post-event action to the cited CISA guidance rather than an unsupplied plan.",
  }),
  setValue({
    id: "gpt_mocsic_2026_07_15_dc_disaster_emergency_preparedness_18_r2",
    path: ["rationale", "byChoice", { refId: "2" }, "zh"],
    before: "计划要求仅在经验证的解除警报后开展临床分诊。",
    after: "收到经验证的解除警报后，工作人员应遵循已发出的指示，并在确保安全时提供临床救助。",
    note: "Chinese parity for the sourced by-choice explanation.",
  }),
  setValue({
    id: "gpt_mocsic_2026_07_15_dc_disaster_emergency_preparedness_18_r2",
    path: ["testTakingStrategy", "en"],
    before: "Separate the security phase from the clinical-response phase: secure first, triage after the verified all-clear.",
    after: "Separate the security phase from the clinical-response phase: remain secured first, then follow authenticated instructions and render aid when safe.",
    note: "Remove the unsupported designated-triage sequence while preserving the phase-order construct.",
  }),
  setValue({
    id: "gpt_mocsic_2026_07_15_dc_disaster_emergency_preparedness_18_r2",
    path: ["testTakingStrategy", "zh"],
    before: "区分安全阶段和临床应对阶段：先就地防护，经验证解除警报后再分诊。",
    after: "区分安全阶段和临床应对阶段：先保持锁闭，再遵循经验证的指示，并在确保安全时提供救助。",
    note: "Chinese parity for the phase-order strategy repair.",
  }),
  setValue({
    id: "gpt_mocsic_2026_07_15_dc_disaster_emergency_preparedness_18_r2",
    path: ["meta", "source"],
    before: "Cybersecurity and Infrastructure Security Agency, Hospitals and Healthcare Facilities Security Action Guide, lockdown, safe-location, patient-security, and device-silencing guidance, https://www.cisa.gov/sites/default/files/publications/19_0515_cisa_action-guide-hospitals-and-healthcare.pdf; the authenticated all-clear and post-event sequence are supplied by the facility plan in the item",
    after: "Cybersecurity and Infrastructure Security Agency, Hospitals and Healthcare Facilities Security Action Guide, hospital lockdown, locked secure-area, and device-silencing guidance, https://www.cisa.gov/sites/default/files/publications/19_0515_cisa_action-guide-hospitals-and-healthcare.pdf; Cybersecurity and Infrastructure Security Agency, Active Shooter Preparedness Action Guide (June 2025), render first aid when safe and follow law-enforcement and first-responder instructions, https://www.cisa.gov/sites/default/files/2025-06/Active-Shooter-Preparedness-Action-Guide_508_20250611.pdf",
    note: "Replace the affirmatively false item-plan source claim with two official CISA primary sources.",
  }),
  setValue({
    id: "gpt_mocsic_2026_07_15_dc_disaster_emergency_preparedness_18_r2",
    path: ["dropdowns", { id: "2" }, "options", { id: "o1" }, "en"],
    before: "begin triage in the designated safe area",
    after: "follow the authenticated instructions and render clinical aid when safe",
    note: "Remove the missing designated-area antecedent and use CISA-supported post-event behavior without changing the key.",
  }),
  setValue({
    id: "gpt_mocsic_2026_07_15_dc_disaster_emergency_preparedness_18_r2",
    path: ["dropdowns", { id: "2" }, "options", { id: "o1" }, "zh"],
    before: "在指定安全区域开始分诊",
    after: "遵循经验证的指示，并在确保安全时提供临床救助",
    note: "Chinese parity for the sourced keyed action.",
  }),
  setValue({
    id: "gpt_mocsic_2026_07_15_dc_disaster_emergency_preparedness_18_r2",
    path: ["dropdowns", { id: "2" }, "options", { id: "o3" }, "en"],
    before: "resume routine unit operations without reporting to the designated safe area",
    after: "resume routine unit operations without following the post-event instructions",
    note: "Remove the same missing designated-area antecedent from the distractor.",
  }),
  setValue({
    id: "gpt_mocsic_2026_07_15_dc_disaster_emergency_preparedness_18_r2",
    path: ["dropdowns", { id: "2" }, "options", { id: "o3" }, "zh"],
    before: "不前往指定安全区域报到，直接恢复病区常规运行",
    after: "不遵循事件后指示，直接恢复病区常规运行",
    note: "Chinese parity for the repaired distractor.",
  }),

  setValue({
    id: "gpt_balance5_2026_07_16_mx_client_advocacy_02_r2",
    path: ["matrix", "rows", { id: "q02_r2" }, "en"],
    before: "If the task is not obvious, ask the two permitted questions described in the stem.",
    after: "If the dog's task were not apparent, ask only whether the dog is required because of a disability and what work or task it has been trained to perform.",
    note: "Make the scored row self-contained by naming the two ADA-permitted questions.",
  }),
  setValue({
    id: "gpt_balance5_2026_07_16_mx_client_advocacy_02_r2",
    path: ["matrix", "rows", { id: "q02_r2" }, "zh"],
    before: "如果服务犬的任务并不明显，询问题干中说明的两个允许问题。",
    after: "如果服务犬的任务并不明显，只询问该犬是否因残障而需要，以及它经过训练可执行什么工作或任务。",
    note: "Chinese parity for the self-contained ADA inquiry row.",
  }),
  setValue({
    id: "gpt_balance5_2026_07_16_mx_client_advocacy_02_r2",
    path: ["meta", "stem_disambiguators"],
    before: [
      "trained seizure-alert service dog",
      "stable inpatient",
      "two permitted questions",
      "specific exclusion reason",
    ],
    after: [
      "trained seizure-alert service dog",
      "stable inpatient",
      "seizure-alert task stated",
      "client-advocacy classification task",
    ],
    note: "Replace two deleted-stem claims with disambiguators that are actually present in the current stem.",
  }),

  setValue({
    id: "gpt_balance5_2026_07_16_hl_disaster_emergency_preparedness_13_r2",
    path: ["rationale", "correct", "en"],
    before: "The activated plan creates controlled identity, tracking, family, and media pathways. Unique temporary identifiers and a current tracking list reduce misidentification; family inquiries and public information are routed through their designated functions.",
    after: "Safe mass-casualty response uses controlled identity, tracking, family, and media pathways. Separate temporary identifiers and a current tracking list reduce misidentification; family inquiries and public information are routed through designated functions.",
    note: "Remove the unsupported assertion about what the unsupplied activated plan creates.",
  }),
  setValue({
    id: "gpt_balance5_2026_07_16_hl_disaster_emergency_preparedness_13_r2",
    path: ["rationale", "correct", "zh"],
    before: "已启动的计划建立了受控的身份、追踪、家属和媒体信息通道。临时唯一标识和最新追踪清单可减少身份错误；家属查询和公共信息分别通过指定职能处理。",
    after: "安全的大规模伤亡事件应对采用受控的身份、追踪、家属和媒体信息通道。分别使用临时标识并维护最新追踪清单可减少身份错误；家属查询和公共信息应通过指定职能处理。",
    note: "Chinese parity for removal of the unsupported plan assertion.",
  }),
  setValue({
    id: "gpt_balance5_2026_07_16_hl_disaster_emergency_preparedness_13_r2",
    path: ["rationale", "byChoice", { refId: "q13_s4" }, "en"],
    before: "The plan assigns media release to the public-information function, not bedside staff.",
    after: "Media requests belong with the hospital's public-information function, not bedside staff.",
    note: "Remove the unsupported assignment-to-plan claim.",
  }),
  setValue({
    id: "gpt_balance5_2026_07_16_hl_disaster_emergency_preparedness_13_r2",
    path: ["rationale", "byChoice", { refId: "q13_s4" }, "zh"],
    before: "该计划把媒体信息发布交给公共信息职能，而不是床旁工作人员。",
    after: "媒体请求应由医院的公共信息职能处理，而不是由床旁工作人员处理。",
    note: "Chinese parity for removal of the unsupported plan claim.",
  }),
  setValue({
    id: "gpt_balance5_2026_07_16_hl_disaster_emergency_preparedness_13_r2",
    path: ["rationale", "byChoice", { refId: "q13_s6" }, "en"],
    before: "Public posting bypasses the designated reunification and information-management process.",
    after: "Public posting bypasses controlled reunification and information management.",
    note: "Remove the implication that a detailed designated process was supplied in the stem.",
  }),
  setValue({
    id: "gpt_balance5_2026_07_16_hl_disaster_emergency_preparedness_13_r2",
    path: ["rationale", "byChoice", { refId: "q13_s6" }, "zh"],
    before: "公开发布照片绕过了指定的团聚和信息管理流程。",
    after: "公开发布会绕过受控的家属团聚和信息管理流程。",
    note: "Chinese parity for the self-contained explanation.",
  }),
  setValue({
    id: "gpt_balance5_2026_07_16_hl_disaster_emergency_preparedness_13_r2",
    path: ["rationale", "byChoice", { refId: "q13_s7" }, "en"],
    before: "Unverified bedside disclosure violates the designated information-management process and may spread misinformation.",
    after: "Unverified bedside disclosure may spread misinformation and bypasses coordinated public-information handling.",
    note: "Remove reliance on an unsupplied designated process.",
  }),
  setValue({
    id: "gpt_balance5_2026_07_16_hl_disaster_emergency_preparedness_13_r2",
    path: ["rationale", "byChoice", { refId: "q13_s7" }, "zh"],
    before: "床旁披露未经核实的信息违反指定的信息管理流程，也可能传播错误信息。",
    after: "床旁披露未经核实的信息可能传播错误信息，并绕过协调的公共信息处理流程。",
    note: "Chinese parity for the self-contained explanation.",
  }),
  setValue({
    id: "gpt_balance5_2026_07_16_hl_disaster_emergency_preparedness_13_r2",
    path: ["rationale", "byChoice", { refId: "q13_s8" }, "en"],
    before: "Independent searching increases congestion and bypasses the designated family-reunification process.",
    after: "Independent searching increases congestion and bypasses coordinated family reunification.",
    note: "Remove reliance on an unsupplied designated process.",
  }),
  setValue({
    id: "gpt_balance5_2026_07_16_hl_disaster_emergency_preparedness_13_r2",
    path: ["rationale", "byChoice", { refId: "q13_s8" }, "zh"],
    before: "家属自行搜索会增加拥挤，并绕过指定团聚流程。",
    after: "家属自行搜索会增加拥挤，并绕过协调的家属团聚流程。",
    note: "Chinese parity for the self-contained explanation.",
  }),
  setValue({
    id: "gpt_balance5_2026_07_16_hl_disaster_emergency_preparedness_13_r2",
    path: ["testTakingStrategy", "en"],
    before: "Use the activated plan as the governing protocol. Select only actions that preserve unique identity and route information through the named tracking, family, and media functions.",
    after: "Select actions that preserve one identity per client, maintain traceable location information, and route family and media inquiries through coordinated channels; reject shared identifiers and uncontrolled disclosure.",
    note: "Replace orphaned named-plan references with discriminating criteria.",
  }),
  setValue({
    id: "gpt_balance5_2026_07_16_hl_disaster_emergency_preparedness_13_r2",
    path: ["testTakingStrategy", "zh"],
    before: "把已启动的计划视为应遵循的规程。只选择能够保持唯一身份，并通过指定追踪、家属和媒体职能传递信息的行动。",
    after: "选择能为每名患者保持独立身份、维持可追踪位置信息，并将家属和媒体查询引导至协调渠道的行动；排除共用标识和不受控披露。",
    note: "Chinese parity for the discriminating strategy repair.",
  }),
  setValue({
    id: "gpt_balance5_2026_07_16_hl_disaster_emergency_preparedness_13_r2",
    path: ["meta", "stem_disambiguators"],
    before: [
      "unidentified clients",
      "families and media crowding",
      "temporary unique identifiers",
      "activated closed-world plan",
    ],
    after: [
      "unidentified clients",
      "families and media crowding",
      "mass-casualty plan activated",
      "identity and communication task",
    ],
    note: "Replace deleted-content claims with cues present in the current stem.",
  }),

  setValue({
    id: "gpt_balance6a_2026_07_16_bt_perioperative_care_13_r2",
    path: ["bowtie", "actions", "tokens", { id: "q13_a_support" }, "en"],
    before: "Provide airway/seizure support and begin 20% lipid emulsion per the supplied protocol",
    after: "Provide airway/seizure support and begin 20% lipid emulsion",
    note: "Remove dependence on the deleted supplied-protocol recital while retaining the ASRA-supported keyed action.",
  }),
  setValue({
    id: "gpt_balance6a_2026_07_16_bt_perioperative_care_13_r2",
    path: ["bowtie", "actions", "tokens", { id: "q13_a_support" }, "zh"],
    before: "提供气道和癫痫支持，并按既定流程开始20%脂肪乳",
    after: "提供气道和癫痫支持，并开始给予20%脂肪乳",
    note: "Chinese parity for removal of the unsupplied-protocol dependency.",
  }),

  setValue({
    id: "gpt_balance6b_2026_07_16_dc_confidentiality_hipaa_05_r2",
    path: ["clozeStem", "en"],
    before: "Disclosure of these separately maintained notes generally requires the client's {{q05_d01}}; the fact that the requesting psychiatrist will use them for {{q05_d02}} does not by itself remove that requirement.",
    after: "Disclosure of these separately maintained notes generally requires the client's {{q05_d01}}; this requirement still applies to {{q05_d02}} when no listed exception applies.",
    note: "Make d2 discriminate the psychotherapy-note exception rule rather than requester narrative fit.",
  }),
  setValue({
    id: "gpt_balance6b_2026_07_16_dc_confidentiality_hipaa_05_r2",
    path: ["clozeStem", "zh"],
    before: "披露这些单独保存的笔记通常需要患者的{{q05_d01}}；请求方精神科医生将其用于{{q05_d02}}这一事实本身并不能取消该要求。",
    after: "披露这些单独保存的笔记通常需要患者的{{q05_d01}}；在没有列明例外的情况下，该要求仍适用于{{q05_d02}}。",
    note: "Chinese parity for the rule-discrimination repair.",
  }),
  setValue({
    id: "gpt_balance6b_2026_07_16_dc_confidentiality_hipaa_05_r2",
    path: ["dropdowns", { id: "q05_d02" }, "options", { id: "q05_d02_o01" }, "en"],
    before: "treatment",
    after: "treatment by a clinician who did not create the notes",
    note: "Specify the non-originator treatment use that remains subject to authorization without changing the key.",
  }),
  setValue({
    id: "gpt_balance6b_2026_07_16_dc_confidentiality_hipaa_05_r2",
    path: ["dropdowns", { id: "q05_d02" }, "options", { id: "q05_d02_o01" }, "zh"],
    before: "治疗",
    after: "由未创建该笔记的临床人员用于治疗",
    note: "Chinese parity for the keyed non-originator treatment use.",
  }),
  setValue({
    id: "gpt_balance6b_2026_07_16_dc_confidentiality_hipaa_05_r2",
    path: ["dropdowns", { id: "q05_d02" }, "options", { id: "q05_d02_o02" }, "en"],
    before: "the hospital's quality-assessment health care operations",
    after: "use by the clinician who created the notes for treatment",
    note: "Use a listed psychotherapy-note exception as a rule-based distractor.",
  }),
  setValue({
    id: "gpt_balance6b_2026_07_16_dc_confidentiality_hipaa_05_r2",
    path: ["dropdowns", { id: "q05_d02" }, "options", { id: "q05_d02_o02" }, "zh"],
    before: "医院的质量评估医疗运营",
    after: "由创建该笔记的临床人员将其用于治疗",
    note: "Chinese parity for the originator-use exception distractor.",
  }),
  setValue({
    id: "gpt_balance6b_2026_07_16_dc_confidentiality_hipaa_05_r2",
    path: ["dropdowns", { id: "q05_d02" }, "options", { id: "q05_d02_o03" }, "en"],
    before: "payment review by the client's health plan",
    after: "use by the covered entity in its supervised mental-health training program",
    note: "Use a second listed psychotherapy-note exception as a rule-based distractor.",
  }),
  setValue({
    id: "gpt_balance6b_2026_07_16_dc_confidentiality_hipaa_05_r2",
    path: ["dropdowns", { id: "q05_d02" }, "options", { id: "q05_d02_o03" }, "zh"],
    before: "患者健康计划的付款审核",
    after: "由受 HIPAA 约束实体用于其心理健康监督培训项目",
    note: "Chinese parity for the supervised-training exception distractor.",
  }),
  setValue({
    id: "gpt_balance6b_2026_07_16_dc_confidentiality_hipaa_05_r2",
    path: ["rationale", "correct", "en"],
    before: "Psychotherapy notes that are maintained separately from the medical record receive special HIPAA protection. With no applicable exception, disclosure requires the client's valid written authorization even when another provider requests the notes for treatment.",
    after: "Psychotherapy notes maintained separately from the medical record receive special HIPAA protection. When no listed exception applies, disclosure requires the client's valid written authorization. Treatment by a clinician who did not create the notes remains subject to that requirement; the note originator's treatment use and the covered entity's supervised training program are listed exceptions.",
    note: "Explain the rule-based d2 competitor set and preserve the authorization construct.",
  }),
  setValue({
    id: "gpt_balance6b_2026_07_16_dc_confidentiality_hipaa_05_r2",
    path: ["rationale", "correct", "zh"],
    before: "与普通病历分开保存的心理治疗笔记受到HIPAA的特殊保护。在没有适用例外时，即使另一位医护人员为治疗目的请求这些笔记，也需要患者有效的书面授权。",
    after: "与普通病历分开保存的心理治疗笔记受到 HIPAA 的特殊保护。在没有列明例外时，披露需要患者有效的书面授权。由未创建笔记的临床人员用于治疗仍受该要求约束；笔记创建者用于治疗以及受 HIPAA 约束实体的监督培训项目属于列明例外。",
    note: "Chinese parity for the rule-based rationale.",
  }),
  setValue({
    id: "gpt_balance6b_2026_07_16_dc_confidentiality_hipaa_05_r2",
    path: ["rationale", "byChoice", { refId: "q05_d02" }, "en"],
    before: "The correct purpose is treatment. Unlike ordinary treatment records, psychotherapy notes generally still require authorization for this provider-to-provider treatment disclosure.",
    after: "The correct completion is treatment by a clinician who did not create the notes. HIPAA lists the note originator's treatment use and the covered entity's own supervised mental-health training program as exceptions.",
    note: "Align the explanation with the rule-based keyed and distractor purposes.",
  }),
  setValue({
    id: "gpt_balance6b_2026_07_16_dc_confidentiality_hipaa_05_r2",
    path: ["rationale", "byChoice", { refId: "q05_d02" }, "zh"],
    before: "正确用途是“治疗”。与普通治疗记录不同，医护人员之间为治疗目的披露心理治疗笔记通常仍需要授权。",
    after: "正确填空是“由未创建该笔记的临床人员用于治疗”。HIPAA 将笔记创建者用于治疗，以及受 HIPAA 约束实体自身的心理健康监督培训项目列为例外。",
    note: "Chinese parity for the repaired d2 explanation.",
  }),
  setValue({
    id: "gpt_balance6b_2026_07_16_dc_confidentiality_hipaa_05_r2",
    path: ["meta", "source"],
    before: "HHS Office for Civil Rights, FAQ 558, disclosure of psychotherapy notes through an HIO and the treatment-purpose authorization rule, https://www.hhs.gov/hipaa/for-professionals/faq/558/does-hipaa-permit-a-covered-entity-to-disclose-psychotherapy-notes-to-an-hio/index.html",
    after: "HHS Office for Civil Rights, FAQ 558, non-originator treatment disclosure of psychotherapy notes requires authorization, https://www.hhs.gov/hipaa/for-professionals/faq/558/does-hipaa-permit-a-covered-entity-to-disclose-psychotherapy-notes-to-an-hio/index.html; 45 CFR § 164.508(a)(2), psychotherapy-note authorization rule and listed exceptions, https://www.ecfr.gov/current/title-45/subtitle-A/subchapter-C/part-164/subpart-E/section-164.508",
    note: "Add the primary regulation supporting the two exception-based distractors.",
  }),

  setValue({
    id: "gpt_balance6b_2026_07_16_bt_procedural_complications_dialysis_14_r2",
    path: ["bowtie", "actions", "tokens", { id: "q14_a02" }, "en"],
    before: "Contact the PD team immediately for transfer-set management and the program's prescribed prophylaxis pathway",
    after: "Contact the PD team immediately for evaluation and further management",
    note: "Remove dependence on an unsupplied program pathway while preserving immediate PD-team contact.",
  }),
  setValue({
    id: "gpt_balance6b_2026_07_16_bt_procedural_complications_dialysis_14_r2",
    path: ["bowtie", "actions", "tokens", { id: "q14_a02" }, "zh"],
    before: "立即联系腹膜透析团队，处理转接管并执行项目规定的预防流程",
    after: "立即联系腹膜透析团队进行评估和进一步处理",
    note: "Chinese parity for the self-contained keyed action.",
  }),
  setValue({
    id: "gpt_balance6b_2026_07_16_bt_procedural_complications_dialysis_14_r2",
    path: ["bowtie", "actions", "tokens", { id: "q14_a05" }, "en"],
    before: "Select an antibiotic, dose, and duration without using the program pathway",
    after: "Select an antibiotic, dose, and duration without consulting the PD team",
    note: "Remove the missing program-pathway antecedent from the distractor.",
  }),
  setValue({
    id: "gpt_balance6b_2026_07_16_bt_procedural_complications_dialysis_14_r2",
    path: ["bowtie", "actions", "tokens", { id: "q14_a05" }, "zh"],
    before: "不按照项目流程，自行选择抗生素、剂量和疗程",
    after: "未咨询腹膜透析团队，自行选择抗生素、剂量和疗程",
    note: "Chinese parity for the repaired distractor.",
  }),
  setValue({
    id: "gpt_balance6b_2026_07_16_bt_procedural_complications_dialysis_14_r2",
    path: ["bowtie", "parameters", "tokens", { id: "q14_p02" }, "en"],
    before: "Completion of the PD program's transfer-set, prophylaxis, and follow-up plan",
    after: "Completion of the PD team's directed evaluation and follow-up",
    note: "Remove dependence on an unsupplied program plan while preserving team-directed completion monitoring.",
  }),
  setValue({
    id: "gpt_balance6b_2026_07_16_bt_procedural_complications_dialysis_14_r2",
    path: ["bowtie", "parameters", "tokens", { id: "q14_p02" }, "zh"],
    before: "完成腹膜透析项目规定的转接管处理、预防措施和随访计划",
    after: "完成腹膜透析团队指导的评估和随访",
    note: "Chinese parity for the self-contained keyed follow-up parameter.",
  }),
  setValue({
    id: "gpt_balance6b_2026_07_16_bt_procedural_complications_dialysis_14_r2",
    path: ["rationale", "correct", "en"],
    before: "Exposure of an open PD fluid pathway proximal to an open clamp is wet contamination and carries peritonitis risk even before symptoms develop. The client should stop use, secure the system, and follow the PD team's transfer-set and prophylaxis pathway. Monitoring focuses on early peritonitis symptoms and completion of the program-directed follow-up.",
    after: "Exposure of an open PD fluid pathway proximal to an open clamp is wet contamination and carries peritonitis risk even before symptoms develop. The client should stop use, secure the system, and contact the PD team immediately for evaluation and further management. Monitoring focuses on early peritonitis symptoms and completion of team-directed follow-up.",
    note: "Replace unsupplied pathway claims with independently sourced immediate PD-team management.",
  }),
  setValue({
    id: "gpt_balance6b_2026_07_16_bt_procedural_complications_dialysis_14_r2",
    path: ["rationale", "correct", "zh"],
    before: "开放夹近端的腹膜透析开放液路发生暴露属于湿性污染，即使尚未出现症状，也有腹膜炎风险。患者应停止使用并保护系统，按照腹膜透析团队的转接管处理和预防流程执行。监测重点是早期腹膜炎症状以及是否完成项目规定的随访。",
    after: "开放夹近端的腹膜透析开放液路发生暴露属于湿性污染，即使尚未出现症状，也有腹膜炎风险。患者应停止使用并保护系统，立即联系腹膜透析团队进行评估和进一步处理。监测重点是早期腹膜炎症状以及是否完成团队指导的随访。",
    note: "Chinese parity for the independently sourced management rationale.",
  }),
  setValue({
    id: "gpt_balance6b_2026_07_16_bt_procedural_complications_dialysis_14_r2",
    path: ["rationale", "byChoice", { refId: "q14_c01" }, "en"],
    before: "The open fluid pathway was exposed proximal to an open clamp, meeting the stem's definition of wet contamination.",
    after: "Exposure of the open fluid pathway proximal to an open clamp is wet contamination.",
    note: "Remove the false claim that the stem supplies a wet-contamination definition.",
  }),
  setValue({
    id: "gpt_balance6b_2026_07_16_bt_procedural_complications_dialysis_14_r2",
    path: ["rationale", "byChoice", { refId: "q14_c01" }, "zh"],
    before: "开放夹近端的开放液路发生暴露，符合题干给出的湿性污染定义。",
    after: "开放夹近端的开放液路发生暴露属于湿性污染。",
    note: "Chinese parity for removal of the false stem-definition claim.",
  }),
  setValue({
    id: "gpt_balance6b_2026_07_16_bt_procedural_complications_dialysis_14_r2",
    path: ["rationale", "byChoice", { refId: "q14_a02" }, "en"],
    before: "The PD team directs transfer-set management and prophylaxis after wet contamination.",
    after: "Immediate PD-team contact is recommended after exchange contamination so the team can direct further management.",
    note: "Align the explanation with the self-contained keyed action and ISPD guidance.",
  }),
  setValue({
    id: "gpt_balance6b_2026_07_16_bt_procedural_complications_dialysis_14_r2",
    path: ["rationale", "byChoice", { refId: "q14_a02" }, "zh"],
    before: "湿性污染后，应由腹膜透析团队指导转接管处理和预防措施。",
    after: "换液过程中发生污染后，应立即联系腹膜透析团队，由团队指导进一步处理。",
    note: "Chinese parity for the sourced PD-team-contact explanation.",
  }),
  setValue({
    id: "gpt_balance6b_2026_07_16_bt_procedural_complications_dialysis_14_r2",
    path: ["rationale", "byChoice", { refId: "q14_a05" }, "en"],
    before: "The item intentionally defers drug selection, dose, and duration to the prescribed program pathway.",
    after: "The client should not independently select an antibiotic, dose, or duration; the PD team directs that management.",
    note: "Remove the item/program reference and state the sourced team-directed boundary.",
  }),
  setValue({
    id: "gpt_balance6b_2026_07_16_bt_procedural_complications_dialysis_14_r2",
    path: ["rationale", "byChoice", { refId: "q14_a05" }, "zh"],
    before: "本题明确把药物选择、剂量和疗程交由项目规定流程决定。",
    after: "患者不应自行选择抗生素、剂量或疗程；这些处理应由腹膜透析团队指导。",
    note: "Chinese parity for the team-directed management boundary.",
  }),
  setValue({
    id: "gpt_balance6b_2026_07_16_bt_procedural_complications_dialysis_14_r2",
    path: ["rationale", "byChoice", { refId: "q14_p02" }, "en"],
    before: "Completion of the directed transfer-set, prophylaxis, and follow-up plan verifies management of the contamination event.",
    after: "Completion of the PD team's directed evaluation and follow-up verifies management of the contamination event.",
    note: "Remove dependence on an unsupplied plan.",
  }),
  setValue({
    id: "gpt_balance6b_2026_07_16_bt_procedural_complications_dialysis_14_r2",
    path: ["rationale", "byChoice", { refId: "q14_p02" }, "zh"],
    before: "完成规定的转接管处理、预防和随访计划，可核实该污染事件已得到管理。",
    after: "完成腹膜透析团队指导的评估和随访，可核实该污染事件已得到管理。",
    note: "Chinese parity for the self-contained follow-up explanation.",
  }),
  setValue({
    id: "gpt_balance6b_2026_07_16_bt_procedural_complications_dialysis_14_r2",
    path: ["rationale", "byChoice", { refId: "q14_p05" }, "en"],
    before: "The learner should not invent a fixed prophylactic regimen; the program pathway determines it.",
    after: "A fixed prophylactic regimen should not be invented; the PD team determines the appropriate management.",
    note: "Remove the unsupplied program-pathway reference.",
  }),
  setValue({
    id: "gpt_balance6b_2026_07_16_bt_procedural_complications_dialysis_14_r2",
    path: ["rationale", "byChoice", { refId: "q14_p05" }, "zh"],
    before: "答题者不应臆造固定预防方案；具体方案由项目流程决定。",
    after: "不应臆造固定预防方案；适当处理应由腹膜透析团队决定。",
    note: "Chinese parity for removal of the unsupplied pathway reference.",
  }),
  setValue({
    id: "gpt_balance6b_2026_07_16_bt_procedural_complications_dialysis_14_r2",
    path: ["rationale", "byChoice", { refId: "q14_p04" }, "en"],
    before: "Appetite is nonspecific and does not replace symptom monitoring or program follow-up.",
    after: "Appetite is nonspecific and does not replace symptom monitoring or team-directed follow-up.",
    note: "Remove the final unsupplied-program reference found by the mandatory coherence scan.",
  }),
  setValue({
    id: "gpt_balance6b_2026_07_16_bt_procedural_complications_dialysis_14_r2",
    path: ["rationale", "byChoice", { refId: "q14_p04" }, "zh"],
    before: "食欲缺乏特异性，不能替代症状监测或项目随访。",
    after: "食欲缺乏特异性，不能替代症状监测或团队指导的随访。",
    note: "Chinese parity for removal of the final unsupplied-program reference.",
  }),
  setValue({
    id: "gpt_balance6b_2026_07_16_bt_procedural_complications_dialysis_14_r2",
    path: ["testTakingStrategy", "en"],
    before: "In a contamination item, use the stated open-versus-closed pathway definition, act before symptoms appear, and avoid inventing an antimicrobial regimen.",
    after: "Determine whether contamination reached an open PD fluid pathway, act before symptoms appear, and defer antimicrobial selection to the PD team.",
    note: "Remove the false stated-definition reference and retain source-grounded decision criteria.",
  }),
  setValue({
    id: "gpt_balance6b_2026_07_16_bt_procedural_complications_dialysis_14_r2",
    path: ["testTakingStrategy", "zh"],
    before: "在污染题中，应使用题干给出的开放/关闭液路定义，在症状出现前采取行动，并避免臆造抗菌药方案。",
    after: "判断污染是否到达开放的腹膜透析液路，在症状出现前采取行动，并将抗菌药选择交由腹膜透析团队决定。",
    note: "Chinese parity for the source-grounded strategy.",
  }),
  setValue({
    id: "gpt_balance6b_2026_07_16_bt_procedural_complications_dialysis_14_r2",
    path: ["meta", "stem_disambiguators"],
    before: [
      "transfer set disconnects proximal to open clamp",
      "open system exposed",
      "asymptomatic at call",
      "program pathway supplied",
    ],
    after: [
      "transfer set disconnects proximal to open clamp",
      "open system exposed",
      "asymptomatic at call",
      "immediate call after reconnection",
    ],
    note: "Replace the false supplied-program claim with a cue present in the current stem.",
  }),

  setValue({
    id: "gpt_balance6b_2026_07_16_hl_standard_precautions_hygiene_17_r2",
    path: ["highlight", "segments", { id: "q17_s04" }, "en"],
    before: "Maintain natural nail tips at or below the stated 1/4-inch limit.",
    after: "Keep natural nail tips short and well maintained.",
    note: "Remove the orphaned stated-limit reference and the precision cue from scored text without changing the keyed segment.",
  }),
  setValue({
    id: "gpt_balance6b_2026_07_16_hl_standard_precautions_hygiene_17_r2",
    path: ["highlight", "segments", { id: "q17_s04" }, "zh"],
    before: "自然指甲尖端保持在规定的1/4英寸以内。",
    after: "保持自然指甲尖端短且维护良好。",
    note: "Chinese parity for removal of the orphaned numeric limit.",
  }),
  setValue({
    id: "gpt_balance6b_2026_07_16_hl_standard_precautions_hygiene_17_r2",
    path: ["rationale", "correct", "en"],
    before: "Artificial fingernail extensions are not appropriate for direct contact with high-risk ICU or operating-room patients. The nurse should comply with the facility nail policy, keep natural nails within the stated length, and perform indicated hand hygiene. Gloves or longer scrubbing do not replace the restriction, and the cited rule does not establish a universal ban on intact nail polish.",
    after: "Artificial fingernail extensions are not appropriate for direct contact with high-risk ICU or operating-room patients. The nurse should comply with the facility nail policy, keep natural nail tips short, and perform indicated hand hygiene. Gloves or longer scrubbing do not replace the restriction, and CDC guidance does not establish a universal ban on intact nail polish.",
    note: "Remove orphaned stated/cited-rule references and align with the repaired keyed segment.",
  }),
  setValue({
    id: "gpt_balance6b_2026_07_16_hl_standard_precautions_hygiene_17_r2",
    path: ["rationale", "correct", "zh"],
    before: "与高风险ICU或手术室患者直接接触时，不应佩戴人工指甲延长物。护士应遵守机构指甲政策，把自然指甲保持在规定长度内，并在规定时机执行手卫生。手套或延长刷洗时间不能替代该限制；所引用规则也没有规定完整无损的指甲油在所有环境中一律禁止。",
    after: "与高风险ICU或手术室患者直接接触时，不应佩戴人工指甲延长物。护士应遵守机构指甲政策，保持自然指甲尖端短，并在规定时机执行手卫生。手套或延长刷洗时间不能替代该限制；CDC 指南也没有规定完整无损的指甲油在所有环境中一律禁止。",
    note: "Chinese parity for removal of orphaned rule references.",
  }),
  setValue({
    id: "gpt_balance6b_2026_07_16_hl_standard_precautions_hygiene_17_r2",
    path: ["rationale", "byChoice", { refId: "q17_s04" }, "en"],
    before: "The stem supplies the accepted natural-nail length limit that should be followed.",
    after: "CDC guidance recommends keeping natural nail tips short, at less than 1/4 inch.",
    note: "Replace the false stem-supplied claim with the cited CDC recommendation in post-answer rationale.",
  }),
  setValue({
    id: "gpt_balance6b_2026_07_16_hl_standard_precautions_hygiene_17_r2",
    path: ["rationale", "byChoice", { refId: "q17_s04" }, "zh"],
    before: "题干给出了应遵守的自然指甲长度上限。",
    after: "CDC 指南建议保持自然指甲尖端较短，即短于1/4英寸。",
    note: "Chinese parity for the sourced post-answer length explanation.",
  }),
  setValue({
    id: "gpt_balance6b_2026_07_16_hl_standard_precautions_hygiene_17_r2",
    path: ["testTakingStrategy", "en"],
    before: "Use the exact population and rule in the stem: high-risk direct care triggers the artificial-extension restriction, while unrelated universal claims are distractors.",
    after: "Focus on the high-risk direct-care setting and distinguish supported nail and hand-hygiene practices from claims that gloves, extra scrubbing, or universal polish bans replace the guidance.",
    note: "Remove the false exact-rule-in-stem claim and provide discriminating criteria.",
  }),
  setValue({
    id: "gpt_balance6b_2026_07_16_hl_standard_precautions_hygiene_17_r2",
    path: ["testTakingStrategy", "zh"],
    before: "使用题干中的具体人群和规则：高风险直接护理触发人工指甲限制，与此无关的一概而论是干扰项。",
    after: "聚焦高风险直接护理情境，区分有依据的指甲和手卫生做法，以及声称手套、延长刷洗或全面禁用指甲油可替代指南的说法。",
    note: "Chinese parity for the discriminating strategy repair.",
  }),
  setValue({
    id: "gpt_balance6b_2026_07_16_hl_standard_precautions_hygiene_17_r2",
    path: ["meta", "stem_disambiguators"],
    before: [
      "artificial fingernail extensions",
      "direct ICU care",
      "natural nail limit supplied",
    ],
    after: [
      "artificial fingernail extensions",
      "direct ICU care",
      "facility policy and CDC guidance",
    ],
    note: "Replace the false supplied-limit claim with authority actually named in the stem.",
  }),
] as const;

export const addedFactSources = [
  {
    id: "gpt_mocsic_2026_07_15_dc_disaster_emergency_preparedness_18_r2",
    fact: "After the threat phase, follow authenticated law-enforcement/first-responder instructions and render aid when safe.",
    source: "CISA Active Shooter Preparedness Action Guide (June 2025), https://www.cisa.gov/sites/default/files/2025-06/Active-Shooter-Preparedness-Action-Guide_508_20250611.pdf",
  },
  {
    id: "gpt_balance5_2026_07_16_mx_client_advocacy_02_r2",
    fact: "When a service-dog task is not apparent, staff may ask only whether the dog is required because of a disability and what work or task it is trained to perform.",
    source: "U.S. Department of Justice, Frequently Asked Questions about Service Animals and the ADA, Q7, https://www.ada.gov/resources/service-animals-faqs/",
  },
  {
    id: "gpt_balance6b_2026_07_16_dc_confidentiality_hipaa_05_r2",
    fact: "Non-originator treatment use remains subject to authorization, while originator treatment use and the covered entity's supervised mental-health training program are listed exceptions.",
    source: "45 CFR § 164.508(a)(2), https://www.ecfr.gov/current/title-45/subtitle-A/subchapter-C/part-164/subpart-E/section-164.508; HHS OCR FAQ 558, https://www.hhs.gov/hipaa/for-professionals/faq/558/does-hipaa-permit-a-covered-entity-to-disclose-psychotherapy-notes-to-an-hio/index.html",
  },
] as const;

if (process.argv.includes("--print-ops-json")) {
  process.stdout.write(`${JSON.stringify(ops, null, 2)}\n`);
} else if (process.argv.includes("--print-added-facts-json")) {
  process.stdout.write(`${JSON.stringify(addedFactSources, null, 2)}\n`);
} else if (process.argv.includes("--apply-coherence-followup-only")) {
  runPatch([
    ...ops.filter((op) => op.note?.includes("final unsupplied-program reference")),
  ]);
} else {
  runPatch([...ops]);
}
