import { copyFileSync, mkdtempSync, readFileSync, rmSync } from "node:fs";
import { basename, join, resolve } from "node:path";
import { tmpdir } from "node:os";
import { spawnSync } from "node:child_process";
import { fileURLToPath, pathToFileURL } from "node:url";
import { runPatch, setValue, type JsonPath, type PatchOp, type PathSegment } from "../patch-raw";

type BankName = "burn-canonical.json" | "gpt-canonical.json" | "hard-cases-canonical.json" | "io-canonical.json";

export const PRODUCER_VOCABULARY_PATCHES: Record<BankName, PatchOp[]> = {
  "burn-canonical.json": [
    setValue({ id: "burn_mc_resuscitation_threshold_02", path: ["rationale", "byChoice", { refId: "C" }, "en"], before: "The client is an adult, and this lane uses adult Rule-of-Nines values rather than pediatric charts.", after: "The client is an adult, so this item uses adult Rule-of-Nines values rather than pediatric charts." }),
  ],
  "gpt-canonical.json": [
    setValue({ id: "gpt_2026_07_03_2114_t1_06_dka_fluid_fib", path: ["rationale", "correct", "en"], before: "Use the closed-world order set: 15 mL/kg × 64 kg = 960 mL during the first hour. The item asks for volume, not mL/hr beyond the first-hour order.", after: "Use the order set stated in the stem: 15 mL/kg × 64 kg = 960 mL during the first hour. The item asks for volume, not mL/hr beyond the first-hour order." }),
    setValue({ id: "gpt_2026_07_03_2114_t2_04_kcl_duration_fib", path: ["rationale", "correct", "en"], before: "Using the stated policy, divide the total dose by the maximum peripheral rate: 40 mEq ÷ 10 mEq/hr = 4 hours. Faster administration would exceed the closed-world safety rule in the stem.", after: "Using the stated policy, divide the total dose by the maximum peripheral rate: 40 mEq ÷ 10 mEq/hr = 4 hours. Faster administration would exceed the safety limit stated in the stem." }),
    setValue({ id: "gpt_2026_07_03_2114_t2_05_palliative_dyspnea_dropdown", path: ["rationale", "correct", "en"], before: "The closed-world care plan prioritizes dyspnea relief over numeric oxygen targets. Prescribed low-dose morphine can be used for end-of-life dyspnea while the nurse explains the comfort goal and monitors the client's response.", after: "The care plan stated in the stem prioritizes dyspnea relief over numeric oxygen targets. Prescribed low-dose morphine can be used for end-of-life dyspnea while the nurse explains the comfort goal and monitors the client's response." }),
    setValue({ id: "gpt_2026_07_03_2114_t3_insulin_correction_fib_04", path: ["rationale", "correct", "en"], before: "The blood glucose value of 312 mg/dL falls in the 301-350 mg/dL correction-scale range, so the nurse administers 8 units of insulin lispro according to the closed-world order.", after: "The blood glucose value of 312 mg/dL falls in the 301-350 mg/dL correction-scale range, so the nurse administers 8 units of insulin lispro according to the order stated in the stem." }),
    setValue({ id: "gpt_balance3_2026_07_16_hl_disaster_emergency_preparedness_13", path: ["rationale", "correct", "en"], before: "The safe response follows the closed-world downtime plan: use controlled paper records, verify identity without barcode scanning, read back critical results, document medications as they are given, and reconcile before retrospective entry. Personal texting and memory-based reconstruction create privacy and medication-safety risks.", after: "The safe response follows the downtime plan stated in the case: use controlled paper records, verify identity without barcode scanning, read back critical results, document medications as they are given, and reconcile before retrospective entry. Personal texting and memory-based reconstruction create privacy and medication-safety risks." }),
    setValue({ id: "gpt_balance5_2026_07_16_hl_conflict_resolution_03", path: ["rationale", "byChoice", { refId: "q03_s6" }, "en"], before: "The stated workflow is the closed-world process that restores complete and orderly interpretation.", after: "The stated workflow is the process that restores complete and orderly interpretation." }),
    setValue({ id: "gpt_balance5_2026_07_16_hl_disaster_emergency_preparedness_13", path: ["testTakingStrategy", "en"], before: "Use the activated plan as a closed world. Select only actions that preserve unique identity and route information through the named tracking, family, and media functions.", after: "Use the activated plan as the governing protocol. Select only actions that preserve unique identity and route information through the named tracking, family, and media functions." }),
    setValue({ id: "gpt_balance6a_2026_07_16_or_procedural_complications_dialysis_14", path: ["rationale", "correct", "en"], before: "Cloudy effluent with abdominal pain requires prompt evaluation for PD peritonitis. Under the stated stable, closed-world pathway, notify the PD clinician, collect the specified effluent studies before the first antibiotic dose without dangerous delay, start prescribed empiric therapy promptly, and then reassess clinical response and results to refine treatment.", after: "Cloudy effluent with abdominal pain requires prompt evaluation for PD peritonitis. Under the pathway stated in the stem for a stable client, notify the PD clinician, collect the specified effluent studies before the first antibiotic dose without dangerous delay, start prescribed empiric therapy promptly, and then reassess clinical response and results to refine treatment." }),
    setValue({ id: "gpt_casepilot_2026_07_19_c_case", path: ["caseStudy", "questions", { id: "gpt_casepilot_2026_07_19_c_part_3_stimulation_purpose" }, "rationale", "byChoice", { refId: "a" }, "en"], before: "Correct. This is the source-supported context for considering the maneuver after review.", after: "Correct. This clinical context supports considering the maneuver after review." }),
    setValue({ id: "gpt_deepen_2026_06_22_b_moc1_01", path: ["rationale", "byChoice", { refId: "c_rrt_postop_bleeding" }, "en"], before: "Correct. Hypotension, tachycardia, new confusion, pallor, and a saturated dressing meet the closed-world escalation rule.", after: "Correct. Hypotension, tachycardia, new confusion, pallor, and a saturated dressing meet the escalation criteria stated in the stem." }),
    setValue({ id: "gpt_deepen_2026_06_22_b_moc1_02", path: ["rationale", "byChoice", { refId: "a_withhold_o2" }, "en"], before: "Incorrect. This misreads DNR as a general refusal of treatment, which the closed-world policy rejects.", after: "Incorrect. This misreads DNR as a general refusal of treatment, which the policy stated in the stem rejects." }),
    setValue({ id: "gpt_deepen_2026_06_22_b_moc1_03", path: ["rationale", "byChoice", { refId: "c_red_rr" }, "en"], before: "Correct. The closed-world START card keys RR greater than 30/min as red.", after: "Correct. The START card in the stem classifies a respiratory rate greater than 30/min as red." }),
    setValue({ id: "gpt_deepen_2026_06_22_b_moc1_04", path: ["rationale", "byChoice", { refId: "a_start_cpr" }, "en"], before: "Incorrect. Starting CPR would violate the verified active DNR/POLST in the closed-world policy.", after: "Incorrect. Starting CPR would violate the verified active DNR/POLST under the policy stated in the stem." }),
    setValue({ id: "gpt_deepen_2026_06_22_b_moc1_06", path: ["rationale", "byChoice", { refId: "E" }, "en"], before: "This follows the failed prescriber clarification and precedes higher chain-of-command escalation in the closed-world policy.", after: "This follows the failed prescriber clarification and precedes higher chain-of-command escalation under the policy stated in the stem." }),
    setValue({ id: "gpt_deepen_2026_06_23_bow_02", path: ["rationale", "correct", "en"], before: "Thrombocytopenia with prolonged PT/aPTT, very low fibrinogen, and markedly elevated D-dimer is the closed-world DIC pattern in the stem. The priority is rapid escalation, bleeding precautions, and preparation for ordered component therapy while trending coagulation and bleeding status.", after: "Thrombocytopenia with prolonged PT/aPTT, very low fibrinogen, and markedly elevated D-dimer form the DIC pattern described in the stem. The priority is rapid escalation, bleeding precautions, and preparation for ordered component therapy while trending coagulation and bleeding status." }),
    setValue({ id: "gpt_deepen_2026_06_23_cue_02", path: ["rationale", "correct", "en"], before: "The keyed findings meet the closed-world escalation rule in the stem: high CIWA-Ar score, hallucination with impaired reality testing, fever/tachycardia above threshold, and disorientation.", after: "The keyed findings meet the escalation criteria stated in the stem: high CIWA-Ar score, hallucination with impaired reality testing, fever/tachycardia above threshold, and disorientation." }),
    setValue({ id: "gpt_deepen_2026_06_23_cue_10", path: ["rationale", "correct", "en"], before: "The selected segments violate the closed-world policy: restraints were used without documenting less-restrictive attempts, tied to side rails, sedating medication was followed by delayed respiratory/sedation monitoring, and required restraint checks were deferred.", after: "The selected segments violate the policy stated in the stem: restraints were used without documenting less-restrictive attempts, tied to side rails, sedating medication was followed by delayed respiratory/sedation monitoring, and required restraint checks were deferred." }),
    setValue({ id: "gpt_format10c_parenteral_nutrition_discontinuation_plan", path: ["stem", "en"], before: "A client's reliable oral and enteral intake has met the nutrition-support team's individualized non-PN target for 24 hours. The team writes this closed-world discontinuation plan: first verify and document target attainment; adjust the scheduled insulin used specifically for continuous PN; reduce PN to 50% at 1800 for 1 hour; stop PN at 1900; check capillary glucose at 1930. Place the actions in order. The stated times belong to this prescription and are not a universal PN taper.", after: "A client's reliable oral and enteral intake has met the nutrition-support team's individualized non-PN target for 24 hours. The team documents the following parenteral-nutrition discontinuation plan: first verify and document target attainment; adjust the scheduled insulin used specifically for continuous PN; reduce PN to 50% at 1800 for 1 hour; stop PN at 1900; check capillary glucose at 1930. Place the actions in order. The stated times belong to this prescription and are not a universal PN taper." }),
    setValue({ id: "gpt_format11c_microcytic_anemia_localization", path: ["stem", "en"], before: "Interpret three bounded laboratory records. Record A: hemoglobin 9.4 g/dL, MCV 70 fL, ferritin 7 ng/mL, TIBC 472 µg/dL, transferrin saturation 5%, and CRP normal. Record B: hemoglobin 11.2 g/dL, MCV 65 fL, RBC count 6.1 million/mm³, ferritin 92 ng/mL, CRP normal, and HbA2 5.3%. Record C asks for the next confirmation lane for Record B; do not treat the screening pattern as a final genetic diagnosis.", after: "Interpret three bounded laboratory records. Record A: hemoglobin 9.4 g/dL, MCV 70 fL, ferritin 7 ng/mL, TIBC 472 µg/dL, transferrin saturation 5%, and CRP normal. Record B: hemoglobin 11.2 g/dL, MCV 65 fL, RBC count 6.1 million/mm³, ferritin 92 ng/mL, CRP normal, and HbA2 5.3%. Record C asks for the next diagnostic step to confirm the pattern in Record B; do not treat the screening pattern as a final genetic diagnosis." }),
    setValue({ id: "gpt_format11c_microcytic_anemia_localization", path: ["clozeStem", "en"], before: "Record A is most consistent with {{1}}. Record B supports a screening pattern of {{2}}. When definitive confirmation of Record B is required, the next lane is {{3}}.", after: "Record A is most consistent with {{1}}. Record B supports a screening pattern of {{2}}. When definitive confirmation of Record B is required, the next diagnostic step is {{3}}." }),
    setValue({ id: "gpt_format11c_microcytic_anemia_localization", path: ["rationale", "correct", "en"], before: "Record A has depleted iron stores, high binding capacity, and very low transferrin saturation without an inflammatory confounder, supporting iron-deficiency anemia. Record B has marked microcytosis with a relatively high RBC count, preserved ferritin, and elevated HbA2, supporting a beta-thalassemia-trait screening pattern rather than iron deficiency or anemia of chronic inflammation. When definitive confirmation is needed, the next lane is a hemoglobinopathy evaluation with confirmatory molecular testing and genetic counseling as appropriate, not empiric iron or a final genetic label from the screen alone.", after: "Record A has depleted iron stores, high binding capacity, and very low transferrin saturation without an inflammatory confounder, supporting iron-deficiency anemia. Record B has marked microcytosis with a relatively high RBC count, preserved ferritin, and elevated HbA2, supporting a beta-thalassemia-trait screening pattern rather than iron deficiency or anemia of chronic inflammation. When definitive confirmation is needed, the next step is a hemoglobinopathy evaluation with confirmatory molecular testing and genetic counseling as appropriate, not empiric iron or a final genetic label from the screen alone." }),
    setValue({ id: "gpt_format11c_microcytic_anemia_localization", path: ["rationale", "byChoice", { refId: "3" }, "en"], before: "For Record C, confirmatory hemoglobinopathy and molecular testing is the appropriate lane when needed; empiric iron ignores preserved stores, and no further evaluation would overstate a screening result.", after: "For Record C, confirmatory hemoglobinopathy evaluation and molecular testing are the appropriate next steps when needed; empiric iron ignores preserved stores, and no further evaluation would overstate a screening result." }),
    setValue({ id: "gpt_format11c_microcytic_anemia_localization", path: ["testTakingStrategy", "en"], before: "Separate iron-store interpretation from hemoglobinopathy pattern recognition. Ferritin must be read with inflammation, while RBC count and HbA2 point toward a different lane.", after: "Separate iron-store interpretation from hemoglobinopathy pattern recognition. Ferritin must be read with inflammation, while RBC count and HbA2 point toward hemoglobinopathy evaluation." }),
    setValue({ id: "gpt_format7b_inpatient_alcohol_withdrawal_pathway", path: ["testTakingStrategy", "en"], before: "Follow the closed-world pathway in the stem: assess first, activate the prescribed plan, implement monitoring/support, then evaluate the response.", after: "Follow the pathway stated in the stem: assess first, activate the prescribed plan, implement monitoring/support, then evaluate the response." }),
    setValue({ id: "gpt_format8b_palliative_breathlessness_plan", path: ["rationale", "correct", "en"], before: "The closed-world plan proceeds from focused assessment to immediate nonpharmacologic comfort, then the prescribed PRN medicine, timed reassessment, and escalation if distress persists. Routine oxygen is not inserted when symptomatic hypoxemia has not been established.", after: "The plan stated in the stem proceeds from focused assessment to immediate nonpharmacologic comfort, then the prescribed PRN medicine, timed reassessment, and escalation if distress persists. Routine oxygen is not inserted when symptomatic hypoxemia has not been established." }),
    setValue({ id: "gpt_format8b_toddler_unknown_ingestion", path: ["stem", "en"], before: "A conscious, breathing toddler may have swallowed an unknown household product. The child is currently awake, has no seizure, and has no breathing difficulty. Place the closed-world Poison Control pathway in order.", after: "A conscious, breathing toddler may have swallowed an unknown household product. The child is currently awake, has no seizure, and has no breathing difficulty. Place the Poison Control actions described in the scenario in the order the nurse should take them." }),
    setValue({ id: "gpt_format8c_dka_resolution_transition", path: ["stem", "en"], before: "Use this source-pinned lane: DKA is resolved when plasma ketone is below 0.6 mmol/L and venous pH is at least 7.3 or bicarbonate is at least 18 mmol/L; glucose should ideally be below 200 mg/dL. For safe transition, basal subcutaneous insulin must be given with 1–2 hours of overlap before stopping IV insulin. Do not use urine ketones or anion gap alone. Highlight only the note findings that satisfy the resolution lane and safe transition context.", after: "Use the following treatment criteria to determine whether DKA has resolved and whether transition is safe: DKA is resolved when plasma ketone is below 0.6 mmol/L and venous pH is at least 7.3 or bicarbonate is at least 18 mmol/L; glucose should ideally be below 200 mg/dL. For safe transition, basal subcutaneous insulin must be given with 1–2 hours of overlap before stopping IV insulin. Do not use urine ketones or anion gap alone. Highlight only the note findings that satisfy the resolution criteria and safe-transition conditions." }),
    setValue({ id: "gpt_format8c_dka_resolution_transition", path: ["stem", "zh"], before: "使用以下来源限定标准：当血浆酮体低于 0.6 mmol/L，且静脉 pH 至少 7.3 或碳酸氢盐至少 18 mmol/L 时，DKA 可视为缓解；血糖理想情况下低于 200 mg/dL。安全过渡时，应先给予基础皮下胰岛素，并与静脉胰岛素重叠 1–2 小时后再停静脉胰岛素。不要仅依据尿酮或阴离子间隙。请只标出满足缓解标准和安全过渡条件的记录发现。", after: "采用以下治疗标准判断 DKA 是否缓解以及能否安全过渡：当血浆酮体低于 0.6 mmol/L，且静脉 pH 至少 7.3 或碳酸氢盐至少 18 mmol/L 时，DKA 可视为缓解；血糖理想情况下低于 200 mg/dL。安全过渡时，应先给予基础皮下胰岛素，并与静脉胰岛素重叠 1–2 小时后再停静脉胰岛素。不要仅依据尿酮或阴离子间隙。请只标出满足缓解标准和安全过渡条件的记录发现。" }),
    setValue({ id: "gpt_format8c_dka_resolution_transition", path: ["rationale", "byChoice", { refId: "s3" }, "en"], before: "The current pH and bicarbonate both satisfy the supplied acidosis-resolution lane.", after: "The current pH and bicarbonate both satisfy the stated biochemical resolution criteria." }),
    setValue({ id: "gpt_format8c_dka_resolution_transition", path: ["rationale", "byChoice", { refId: "s6" }, "en"], before: "Urine ketones can lag and are not part of the supplied current resolution lane.", after: "Urine ketones can lag and are not part of the current resolution criteria stated in the stem." }),
    setValue({ id: "gpt_format8c_ici_colitis_escalation", path: ["stem", "en"], before: "For this immune-checkpoint-inhibitor follow-up, the source-pinned evaluation/escalation lane is: at least 4 stools per day above baseline, blood or mucus, abdominal pain, fever, dehydration, or peritoneal findings. A single loose stool alone does not cross the lane, and evaluation must still exclude infection. Highlight only the findings that cross the lane.", after: "An oncology nurse reviews a telephone follow-up note for a client receiving an immune checkpoint inhibitor. The oncology service recommends further evaluation for at least 4 stools per day above baseline, blood or mucus in the stool, abdominal pain, fever, signs of dehydration, or peritoneal irritation. One isolated loose stool without other gastrointestinal symptoms does not meet these criteria. Highlight the findings that require further evaluation for possible immune-mediated colitis." }),
    setValue({ id: "gpt_format8c_ici_colitis_escalation", path: ["stem", "zh"], before: "本次免疫检查点抑制剂随访采用以下来源限定的评估/升级标准：每日较基线增加至少 4 次排便，便中带血或黏液，腹痛，发热，脱水，或腹膜刺激征。单次稀便本身不达到标准，评估仍需排除感染。请只标出达到该标准的发现。", after: "肿瘤科护士正在查看一名接受免疫检查点抑制剂治疗患者的电话随访记录。肿瘤科建议对以下情况进一步评估：每日排便次数较基线增加至少 4 次、便中带血或黏液、腹痛、发热、脱水征象或腹膜刺激征。仅有一次稀便且无其他胃肠道症状，不符合这些标准。请标出需要进一步评估是否存在免疫介导性结肠炎的发现。" }),
    setValue({ id: "gpt_format8c_ici_colitis_escalation", path: ["rationale", "correct", "en"], before: "Five watery stools above baseline, blood and mucus, abdominal cramping, fever, and orthostatic dehydration cues all cross the supplied evaluation/escalation lane. One isolated loose stool, unchanged fatigue, and a soft abdomen without guarding do not. The pathway still includes infection assessment rather than assuming every case is immune-mediated colitis.", after: "Six watery stools today—five above the usual baseline of one formed stool daily—along with blood and mucus, abdominal cramping, fever, and orthostatic dehydration cues meet the stated criteria for further evaluation. One isolated loose stool, unchanged fatigue, and a soft abdomen without guarding do not. Infectious causes must also be evaluated before immune-mediated colitis is confirmed." }),
    setValue({ id: "gpt_format8c_ici_colitis_escalation", path: ["rationale", "correct", "zh"], before: "较基线多 5 次水样便、便中血和黏液、腹部绞痛、发热及体位性脱水线索，均达到题干评估/升级标准。单次孤立稀便、未改变的疲劳，以及腹软无肌紧张均未达到。处理路径仍需评估感染，不能把所有情况直接认定为免疫介导性结肠炎。", after: "患者今天共排出 6 次水样便，较平时每日 1 次成形便的基线增加 5 次；同时有便中血和黏液、腹部绞痛、发热及体位性脱水线索，符合题干所述进一步评估标准。单次孤立稀便、未改变的疲劳，以及腹软无肌紧张均不符合。确诊免疫介导性结肠炎前，还必须评估感染性病因。" }),
    setValue({ id: "gpt_format8c_ici_colitis_escalation", path: ["rationale", "byChoice", { refId: "s1" }, "en"], before: "One loose stool without other symptoms does not cross the supplied lane.", after: "One loose stool without other symptoms does not meet the stated criteria." }),
    setValue({ id: "gpt_format8c_ici_colitis_escalation", path: ["rationale", "byChoice", { refId: "s5" }, "en"], before: "Fever crosses the supplied lane and also reinforces the need to assess infection.", after: "Fever meets the stated criteria and also reinforces the need to assess infection." }),
    setValue({ id: "gpt_format8c_ici_colitis_escalation", path: ["rationale", "byChoice", { refId: "s7" }, "en"], before: "Unchanged mild fatigue is nonspecific and does not cross the GI lane.", after: "Unchanged mild fatigue is nonspecific and does not meet the stated gastrointestinal criteria." }),
    setValue({ id: "gpt_format8c_ici_colitis_escalation", path: ["highlight", "segments", { id: "s0" }, "en"], before: "Telephone follow-up note:", after: "Telephone follow-up note: The client's usual baseline is one formed stool daily." }),
    setValue({ id: "gpt_format8c_ici_colitis_escalation", path: ["highlight", "segments", { id: "s0" }, "zh"], before: "电话随访记录：", after: "电话随访记录：患者平时的基线为每日 1 次成形便。" }),
    setValue({ id: "gpt_format8c_ici_colitis_escalation", path: ["highlight", "segments", { id: "s2" }, "en"], before: "Today the client has had five watery stools above the usual daily baseline.", after: "Today the client has had six watery stools total, which is five stools above baseline." }),
    setValue({ id: "gpt_format8c_ici_colitis_escalation", path: ["highlight", "segments", { id: "s2" }, "zh"], before: "今天患者水样便次数比平时每日基线多 5 次。", after: "今天患者共排出 6 次水样便，较基线增加 5 次。" }),
    setValue({ id: "gpt_format8c_ici_colitis_escalation", path: ["highlight", "segments", { id: "s5" }, "en"], before: "Temperature is 38.3 °C.", after: "Temperature is 100.9 °F (38.3 °C)." }),
    setValue({ id: "gpt_format8c_ici_colitis_escalation", path: ["highlight", "segments", { id: "s5" }, "zh"], before: "体温 38.3 °C。", after: "体温为 100.9 °F（38.3 °C）。" }),
    setValue({ id: "gpt_format8c_salicylate_mixed_disorder", path: ["rationale", "byChoice", { refId: "a2" }, "en"], before: "Altered mental status and acute pulmonary compromise are source-supported reasons for early dialysis preparation.", after: "Altered mental status and acute pulmonary compromise support early dialysis preparation." }),
    setValue({ id: "gpt_format9a_npwt_escalation", path: ["rationale", "correct", "en"], before: "Frank bright-red blood in the tubing, new systemic/advancing infection findings, and a therapy interruption beyond 2 hours meet the stated V.A.C. escalation rules. A small stable amount of serosanguineous drainage, an alarm that resolves after correcting a kink, and intact granulating tissue are not independently escalation findings under this closed-world rule.", after: "Frank bright-red blood in the tubing, new systemic/advancing infection findings, and a therapy interruption beyond 2 hours meet the stated V.A.C. escalation rules. A small stable amount of serosanguineous drainage, an alarm that resolves after correcting a kink, and intact granulating tissue are not independently escalation findings under the rule stated in the stem." }),
    setValue({ id: "gpt_format9c_noisy_respiratory_secretions", path: ["rationale", "byChoice", { refId: "3" }, "en"], before: "For dropdown 3, assessment, repositioning, and mouth care are source-supported initial measures; routine deep suction can cause burden, and medication is not automatic solely because the sound is present.", after: "For dropdown 3, assessment, repositioning, and mouth care are appropriate initial measures; routine deep suction can cause burden, and medication is not automatic solely because the sound is present." }),
    setValue({ id: "gpt_format9c_pn_peripheral_central_access", path: ["stem", "en"], before: "Use this closed-world ASPEN teaching lane: peripheral PN may be used for a short anticipated duration when the final osmolarity is no more than 900 mOsm/L and the peripheral site can be closely monitored; more hyperosmolar PN requires central venous administration. A 7-day PN order has a final osmolarity of 820 mOsm/L and is prescribed through a healthy forearm peripheral IV. This item applies the stated lane only; it does not present 900 mOsm/L as a universal law outside this context.", after: "The nutrition-support service uses the following criteria for peripheral and central parenteral nutrition: peripheral PN may be used for a short anticipated duration when the final osmolarity is no more than 900 mOsm/L and the peripheral site can be closely monitored; more hyperosmolar PN requires central venous administration. A 7-day PN order has a final osmolarity of 820 mOsm/L and is prescribed through a healthy forearm peripheral IV. Apply only the criteria stated here; this item does not present 900 mOsm/L as a universal limit outside this context." }),
    setValue({ id: "gpt_format9c_pn_peripheral_central_access", path: ["stem", "zh"], before: "使用以下限定的 ASPEN 教学路径：当预计疗程较短、最终渗透浓度不超过 900 mOsm/L，且可密切监测外周静脉部位时，可采用外周肠外营养；渗透浓度更高的 PN 需要中心静脉给药。一份预计 7 天的 PN 医嘱最终渗透浓度为 820 mOsm/L，拟经健康的前臂外周静脉输注。本题只应用上述限定路径；不把 900 mOsm/L 描述为所有情境下的普遍法律。", after: "营养支持团队采用以下外周和中心静脉肠外营养标准：当预计疗程较短、最终渗透浓度不超过 900 mOsm/L，且可密切监测外周静脉部位时，可采用外周肠外营养；渗透浓度更高的 PN 需要中心静脉给药。一份预计 7 天的 PN 医嘱最终渗透浓度为 820 mOsm/L，拟经健康的前臂外周静脉输注。仅应用此处给出的标准；本题不把 900 mOsm/L 描述为所有情境下的通用上限。" }),
    setValue({ id: "gpt_format9c_pn_peripheral_central_access", path: ["clozeStem", "en"], before: "Within the supplied lane, this order fits {{1}}, and the priority access-related implication is {{2}}. If the same order is reformulated to 1150 mOsm/L, it should instead use {{3}}.", after: "Under the criteria stated in the stem, this order fits {{1}}, and the priority access-related implication is {{2}}. If the same order is reformulated to 1150 mOsm/L, it should instead use {{3}}." }),
    setValue({ id: "gpt_format9c_pn_peripheral_central_access", path: ["clozeStem", "zh"], before: "在题干给出的路径内，该医嘱符合{{1}}，与通路相关的重点是{{2}}。若同一医嘱改配为 1150 mOsm/L，则应改用{{3}}。", after: "根据题干所述标准，该医嘱符合{{1}}，与通路相关的重点是{{2}}。若同一医嘱改配为 1150 mOsm/L，则应改用{{3}}。" }),
    setValue({ id: "gpt_format9c_pn_peripheral_central_access", path: ["rationale", "correct", "en"], before: "Within the supplied ASPEN lane, the short duration and 820 mOsm/L formulation fit peripheral PN. The key nursing implication is frequent assessment of the peripheral site for phlebitis, infiltration, pain, erythema, or loss of patency. If the formulation is changed to 1150 mOsm/L, the same lane supports central venous access with the catheter tip in the central circulation rather than continuing through the peripheral IV.", after: "Under the ASPEN-based criteria stated in the stem, the short duration and 820 mOsm/L formulation fit peripheral PN. The key nursing implication is frequent assessment of the peripheral site for phlebitis, infiltration, pain, erythema, or loss of patency. If the formulation is changed to 1150 mOsm/L, the same criteria support central venous access with the catheter tip in the central circulation rather than continuing through the peripheral IV." }),
    setValue({ id: "gpt_format9c_pn_peripheral_central_access", path: ["rationale", "correct", "zh"], before: "在题干给定的 ASPEN 路径内，短期疗程及 820 mOsm/L 配方符合外周 PN。关键护理监测是频繁评估外周部位是否出现静脉炎、渗漏、疼痛、红斑或通畅性丧失。若配方改为 1150 mOsm/L，同一路径支持使用导管尖端位于中心循环的中心静脉通路，而不是继续通过该外周静脉。", after: "根据题干所述的 ASPEN 标准，短期疗程及 820 mOsm/L 配方符合外周 PN。关键护理监测是频繁评估外周部位是否出现静脉炎、渗漏、疼痛、红斑或通畅性丧失。若配方改为 1150 mOsm/L，同一标准支持使用导管尖端位于中心循环的中心静脉通路，而不是继续通过该外周静脉。" }),
    setValue({ id: "gpt_format9c_pn_peripheral_central_access", path: ["rationale", "byChoice", { refId: "1" }, "en"], before: "For dropdown 1, peripheral PN fits the supplied short-duration, 820 mOsm/L lane; central PN is not required by these facts, and enteral feeding is not the ordered route.", after: "For dropdown 1, peripheral PN fits the stated short-duration and 820 mOsm/L criteria; central PN is not required by these facts, and enteral feeding is not the ordered route." }),
    setValue({ id: "gpt_format9c_pn_peripheral_central_access", path: ["rationale", "byChoice", { refId: "1" }, "zh"], before: "第 1 空中，外周 PN 符合题干给出的短期、820 mOsm/L 路径；这些事实并不要求中心 PN，且肠内营养不是医嘱途径。", after: "第 1 空中，外周 PN 符合题干给出的短期疗程和 820 mOsm/L 标准；这些事实并不要求中心 PN，且肠内营养不是医嘱途径。" }),
    setValue({ id: "gpt_format9c_pn_peripheral_central_access", path: ["rationale", "byChoice", { refId: "3" }, "en"], before: "For dropdown 3, the more hyperosmolar 1150 mOsm/L formulation belongs in central circulation under the supplied lane; the same peripheral IV or a feeding tube would not match the ordered PN route and osmolarity context.", after: "For dropdown 3, the stated criteria place the more hyperosmolar 1150 mOsm/L formulation in central circulation; the same peripheral IV or a feeding tube would not match the ordered PN route and osmolarity context." }),
    setValue({ id: "gpt_format9c_pn_peripheral_central_access", path: ["rationale", "byChoice", { refId: "3" }, "zh"], before: "第 3 空中，在题干路径下，1150 mOsm/L 的高渗配方应进入中心循环；继续使用同一外周静脉或改用喂养管均不符合该 PN 医嘱及渗透浓度背景。", after: "第 3 空中，根据题干所述标准，1150 mOsm/L 的高渗配方应进入中心循环；继续使用同一外周静脉或改用喂养管均不符合该 PN 医嘱及渗透浓度背景。" }),
    setValue({ id: "gpt_format9c_pn_peripheral_central_access", path: ["testTakingStrategy", "en"], before: "Apply the exact lane supplied in the stem: match osmolarity and anticipated duration to access, then choose monitoring that addresses that access.", after: "Apply the exact route-selection criteria stated in the stem: match osmolarity and anticipated duration to access, then choose monitoring that addresses that access." }),
    setValue({ id: "gpt_format9c_pn_peripheral_central_access", path: ["testTakingStrategy", "zh"], before: "严格应用题干给出的路径：根据渗透浓度和预计疗程匹配通路，再选择针对该通路的监测。", after: "严格应用题干给出的通路选择标准：根据渗透浓度和预计疗程匹配通路，再选择针对该通路的监测。" }),
    setValue({ id: "gpt_mocsic_2026_07_15_or_confidentiality_hipaa_08", path: ["rationale", "correct", "en"], before: "The inline policy makes the sequence closed-world: remotely lock or wipe the device, notify privacy/security, document factual loss details without altering evidence, and then complete the formal incident report.", after: "The policy stated in the stem establishes this sequence: remotely lock or wipe the device, notify privacy/security, document factual loss details without altering evidence, and then complete the formal incident report." }),
  ],
  "hard-cases-canonical.json": [
    setValue({ id: "gpt_stroke_2026_06_16_case_acute_ischemic_stroke_warfarin_01", path: ["caseStudy", "questions", { id: "gpt_stroke_2026_06_16_case_acute_ischemic_stroke_warfarin_01_q2" }, "rationale", "correct", "en"], before: "The case states a closed-world institutional protocol: IV alteplase is contraindicated when the INR exceeds 1.7 at intended administration. This client's current stat INR is 1.8, so the nurse should communicate that finding and support rapid CTA and thrombectomy evaluation rather than focusing on the clinic INR from five days ago or assuming a negative CT alone makes alteplase appropriate.", after: "The case states the governing institutional protocol: IV alteplase is contraindicated when the INR exceeds 1.7 at intended administration. This client's current stat INR is 1.8, so the nurse should communicate that finding and support rapid CTA and thrombectomy evaluation rather than focusing on the clinic INR from five days ago or assuming a negative CT alone makes alteplase appropriate." }),
  ],
  "io-canonical.json": [
    setValue({ id: "io_matrix_prerenal_aki_recheck_04", path: ["testTakingStrategy", "en"], before: "Use closed-world thresholds in the stem, then compare them with the visual. Do not assume the goal was met just because fluids were given.", after: "Use the thresholds stated in the stem, then compare them with the visual. Do not assume the goal was met just because fluids were given." }),
  ],
};

const getArg = (flag: string): string | undefined => {
  const index = process.argv.indexOf(flag);
  return index >= 0 ? process.argv[index + 1] : undefined;
};

const selectorValue = (segment: Exclude<PathSegment, string | number>): ["id" | "refId", string] =>
  "id" in segment ? ["id", segment.id] : ["refId", segment.refId];

const resolveValue = (question: unknown, path: JsonPath): unknown => {
  let current = question;
  for (const segment of path) {
    if (typeof segment === "string" || typeof segment === "number") {
      current = (current as Record<string | number, unknown>)[segment];
    } else {
      const [key, value] = selectorValue(segment);
      const matches = (current as unknown[]).filter((entry) => (entry as Record<string, unknown>)[key] === value);
      if (matches.length !== 1) throw new Error(`selector ${key}=${value} matched ${matches.length} entries`);
      current = matches[0];
    }
  }
  return current;
};

const effectiveOps = (bankPath: string, ops: PatchOp[]): PatchOp[] => {
  const bank = JSON.parse(readFileSync(bankPath, "utf8")) as { questions: Array<Record<string, unknown>> };
  const seen = new Set<string>();
  return ops.filter((op) => {
    if (op.kind !== "setValue") throw new Error(`unexpected op kind ${op.kind}`);
    const key = `${op.id}:${JSON.stringify(op.path)}`;
    if (seen.has(key)) throw new Error(`duplicate target path ${key}`);
    seen.add(key);
    const questions = bank.questions.filter((question) => question.id === op.id);
    if (questions.length !== 1) throw new Error(`${op.id} matched ${questions.length} top-level questions`);
    const current = resolveValue(questions[0], op.path);
    if (JSON.stringify(current) === JSON.stringify(op.after)) return false;
    if (JSON.stringify(current) !== JSON.stringify(op.before)) {
      throw new Error(`BLOCKED_REWRITE stale precondition for ${key}`);
    }
    return true;
  });
};

function main(): void {
  const internalBank = getArg("--internal-bank") as BankName | undefined;
  if (internalBank) {
    const input = resolve(getArg("--in") ?? "");
    const pending = effectiveOps(input, PRODUCER_VOCABULARY_PATCHES[internalBank]);
    if (pending.length === 0) {
      console.log(`${internalBank}: idempotent; zero writes`);
      return;
    }
    runPatch(pending);
    return;
  }
  const allowCanonical = process.argv.includes("--allow-canonical");
  const reason = getArg("--reason") ?? "";
  const apply = allowCanonical && reason.trim().length > 0;
  const scriptPath = fileURLToPath(import.meta.url);
  const tempRoot = apply ? null : mkdtempSync(join(tmpdir(), "producer-vocabulary-dry-run-"));
  let totalPending = 0;
  try {
    for (const bank of Object.keys(PRODUCER_VOCABULARY_PATCHES) as BankName[]) {
      const canonicalPath = resolve("banks", bank);
      const pending = effectiveOps(canonicalPath, PRODUCER_VOCABULARY_PATCHES[bank]);
      totalPending += pending.length;
      if (pending.length === 0) {
        console.log(`${bank}: idempotent; zero writes`);
        continue;
      }
      const target = apply ? canonicalPath : join(tempRoot!, bank);
      if (!apply) copyFileSync(canonicalPath, target);
      const child = spawnSync("npx", ["tsx", scriptPath, "--internal-bank", bank, "--in", target, "--out", target, "--allow-canonical", "--reason", apply ? reason : "dry-run simulation only"], { encoding: "utf8", stdio: "pipe" });
      process.stdout.write(child.stdout);
      process.stderr.write(child.stderr);
      if (child.status !== 0) process.exit(child.status ?? 1);
    }
  } finally {
    if (tempRoot) rmSync(tempRoot, { recursive: true, force: true });
  }
  const distinctItems = new Set(Object.values(PRODUCER_VOCABULARY_PATCHES).flat().map((op) => op.id)).size;
  console.log(`Mode: ${apply ? "APPLY" : "DRY RUN"}`);
  console.log(`Affected banks: ${Object.keys(PRODUCER_VOCABULARY_PATCHES).join(", ")}`);
  console.log(`Declared paths: ${Object.values(PRODUCER_VOCABULARY_PATCHES).flat().length}`);
  console.log(`Pending paths: ${totalPending}`);
  console.log(`Distinct top-level items: ${distinctItems}`);
}

if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) main();
