import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { execFileSync } from "node:child_process";

export const REPO = path.resolve(import.meta.dirname, "../../..");
export const ROOT = path.resolve(import.meta.dirname, "..");
export const PROD = "audit/campaign-16-phase-e-stage-reference-census-2026-08-29-r1";
export const CHECK = "audit/campaign-16-phase-e-stage-reference-check-2026-08-29-r1";
export const R1 = "audit/campaign-16-phase-e-residual-192-check-2026-09-02-r1";
export const WORK_ORDER = "scratch/CAMPAIGN-16-PHASE-E-RESIDUAL-192-FULL-SEMANTIC-CHECK-WORK-ORDER-2026-09-03-R2.md";
export const WORK_ORDER_SHA = "a957e1c95a72458d11154f780228723704ee64f5355fb9b017df1495e57a5da5";
export const R1_WORK_ORDER = "scratch/CAMPAIGN-16-PHASE-E-RESIDUAL-192-FULL-SEMANTIC-CHECK-WORK-ORDER-2026-09-02-R1.md";
export const R1_WORK_ORDER_SHA = "5e7c4a5595a75d5bbcdc2a9811dba80495bbf2f3514c90f8237511c0aea061f4";
export const SEED = "campaign16-phase-e-residual192-r1-v1";
export const INSTRUMENT = "campaign16_phase_e_residual_192_v2";
export const MAX_BYTES = 700000;
export const read = (p) => fs.readFileSync(path.join(REPO, p));
export const text = (p) => read(p).toString("utf8");
export const json = (p) => JSON.parse(text(p));
export const jsonl = (p) => text(p).split(/\r?\n/u).filter(Boolean).map((line) => ({ line, row: JSON.parse(line) }));
export const shaBytes = (v) => crypto.createHash("sha256").update(v).digest("hex");
export const sha = (p) => shaBytes(read(p));
export const stable = (v) => Array.isArray(v) ? v.map(stable) : v && typeof v === "object" ? Object.fromEntries(Object.keys(v).sort().map((k) => [k, stable(v[k])])) : v;
export const stableString = (v) => JSON.stringify(stable(v));
export const pretty = (v) => `${JSON.stringify(v, null, 2)}\n`;
export const assert = (condition, message) => { if (!condition) throw new Error(message); };
export const git = (args) => execFileSync("git", args, { cwd: REPO, encoding: "utf8" }).trimEnd();
export const identity = (r) => `${r.queueIndex}\0${r.bankPath}\0${r.parentCaseId}\0${r.partId}`;
export const out = (p) => path.join(ROOT, p);
export const write = (p, body) => fs.writeFileSync(out(p), body);
export const append = (p, value) => fs.appendFileSync(out(p), `${JSON.stringify(value)}\n`);
export const token = (kind, packetId, canonical) => `${kind}_${shaBytes(`${SEED}|${packetId}|${kind}|${canonical}`).slice(0, 28)}`;
export const deepEqual = (a, b) => stableString(a) === stableString(b);
export const fileReceipt = (relativePath) => { const absolute = path.join(REPO, relativePath); const st = fs.statSync(absolute); return { path: relativePath, type: st.isFile() ? "file" : st.isDirectory() ? "directory" : "other", bytes: st.isFile() ? st.size : null, mtime: st.mtime.toISOString(), sha256: st.isFile() ? sha(relativePath) : null }; };
