import { spawn } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
const root=dirname(fileURLToPath(import.meta.url)),batches=Array.from({length:12},(_,i)=>String(i+1).padStart(2,"0"));
const prompt=`You are the independent non-GPT final checker. Stdin is JSONL. Each row contains a frozen blind result, then the hidden live key/rationale/strategy/source, then the primary audit result. Do not alter the blind derivation. Compare blind answer with the key. Decide whether rationale/source cure or confirm any construct defect; distinguish factual support from response-demand support. Apply the strict format gates: bowties need genuinely competing conditions and coherent 1/2/2 value; ordered response must not disclose its own order; dropdown blanks must add independent inferences; fill-in must not be trivial label/acronym recall; stem policy recitals must not give the answer. Assign checkerVerdict PASS/FIX/RETIRE/REVIEW. checkerClass must be VALID_CONSTRUCT or one of WEAK_OR_NONCOMPETING_DIFFERENTIAL, ANSWER_TELEGRAPHING_OR_AUTHORIAL_COMPENSATION, MECHANICAL_CLOZE_DEPENDENCY, NON_NURSING_OR_OVERLY_SPECIALIST_CONSTRUCT, OTHER_CONFIRMED_CONSTRUCT_DEFECT, MULTIPLE_VALID_KEYS, SOURCE_INSUFFICIENCY, BILINGUAL_MATERIAL_DIVERGENCE. checkerDisposition must be KEEP, BOUNDED_TEXT_REPAIR, FULL_ITEM_REWRITE_SAME_CONSTRUCT, RETIRE_WITHOUT_REPLACEMENT, RETIRE_AND_REPLACE_IF_COVERAGE_NEEDED, or OWNER_OR_CLINICAL_ADJUDICATION. Use FIX only when a bounded or full rewrite can preserve the current item; use RETIRE when the current item should leave the bank. Then compare with primary. agreementStatus is AGREE only if verdict/class/disposition materially agree, DISAGREE for PASS-versus-adverse or retirement disagreement, otherwise PARTIAL. Return ONLY compact JSONL, one line per input row, no markdown. Fields: populationIndex,id,checkerVerdict,checkerClass,checkerDisposition,keyComparison,sourceVerification,agreementStatus,disagreementExplanation,ownerDecisionRequirement,reason.`;
const count=(p:string)=>readFileSync(p,"utf8").trim().split("\n").filter(Boolean).length;
function run(n:string){return new Promise<void>((resolve,reject)=>{
  const inp=join(root,"checker-batches",`final6-input-${n}.jsonl`),out=join(root,"checker-batches",`final6-output-${n}.jsonl`),input=readFileSync(inp,"utf8");
  if(existsSync(out)&&count(out)===count(inp)){resolve();return;}
  const child=spawn("gemini",["--skip-trust","--approval-mode","plan","-m","gemini-3.6-flash","-o","text","-p",prompt],{cwd:root,stdio:["pipe","pipe","pipe"]});
  let stdout="",stderr="";child.stdout.on("data",d=>stdout+=d);child.stderr.on("data",d=>stderr+=d);child.stdin.end(input);
  child.on("exit",code=>{try{if(code!==0)throw new Error(`exit ${code}: ${stderr}`);const parsed=stdout.split("\n").map(x=>x.trim()).filter(x=>x.startsWith("{")).map(JSON.parse),expected=input.trim().split("\n").map(JSON.parse);if(parsed.length!==expected.length)throw new Error(`count ${parsed.length}/${expected.length}: ${stdout}`);expected.forEach((x,i)=>{if(x.id!==parsed[i].id||x.populationIndex!==parsed[i].populationIndex)throw new Error(`identity ${n}/${i}`)});writeFileSync(out,parsed.map(JSON.stringify).join("\n")+"\n");resolve();}catch(e){reject(e)}});
})}
for(let i=0;i<batches.length;i+=3)await Promise.all(batches.slice(i,i+3).map(run));
console.log("Gemini final checker complete: 72 rows / 12 files");
