import { mkdir, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import { TOPIC_CATEGORY_ORDER, topicsByCategory } from "../src/topics";

const outputPath = process.argv[2] ?? "docs/topic-vocabulary.md";
const topics = topicsByCategory();

const lines = [
  "# Topic Vocabulary",
  "",
  "Status: candidate vocabulary pending final human topic-list and STRICT/SHARED review.",
  "",
  "Generated from `src/topics.ts`. Do not edit this file by hand; run `npm run export-topic-vocab`.",
  "",
  "| Category | Allowed topics |",
  "|---|---|",
  ...TOPIC_CATEGORY_ORDER.map((category) => `| ${category} | ${topics[category].join("; ")} |`),
];

await mkdir(dirname(outputPath), { recursive: true });
await writeFile(outputPath, `${lines.join("\n")}\n`);
console.log(`Wrote ${outputPath}`);
