import type { ItemType } from "./types";

export const allowedKeySets = {
  bank: ["meta", "questions"],
  bankMeta: ["schemaVersion", "exam", "topic", "category", "difficulty", "count"],
  questionCommon: [
    "id",
    "itemType",
    "category",
    "topic",
    "difficulty",
    "ngnSkill",
    "stem",
    "rationale",
    "testTakingStrategy",
    "glossary",
    "visual",
    "meta",
  ],
  questionByItemType: {
    multiple_choice: ["options", "correct"],
    select_all: ["options", "correct"],
    ordered_response: ["options", "correct"],
    fill_in_blank: ["blanks"],
    matrix: ["matrix", "correct"],
    dropdown_cloze: ["clozeStem", "dropdowns"],
    highlight: ["highlight"],
    bowtie: ["bowtie"],
    case_study: ["caseStudy"],
  } satisfies Record<ItemType, readonly string[]>,
  caseSubQuestion: ["stageId", "answerableAfterStageId"],
  textPair: ["en", "zh"],
  rationale: ["correct", "byChoice", "visuals"],
  rationaleChoice: ["refId", "en", "zh"],
  glossaryTerm: ["termEn", "termZh", "defZh"],
  option: ["id", "en", "zh"],
  blank: ["id", "prompt", "acceptable", "numeric"],
  blankNumeric: ["value", "tolerance", "unit"],
  matrix: ["rows", "columns", "selectionMode"],
  matrixCorrect: ["rowId", "columnIds"],
  dropdown: ["id", "options", "correct"],
  highlight: ["segments", "correct"],
  highlightSegment: ["id", "en", "zh", "selectable"],
  bowtie: ["condition", "actions", "parameters"],
  bowtieZone: ["prompt", "tokens", "correct"],
  bowtieToken: ["id", "en", "zh"],
  caseStudy: ["title", "summary", "exhibits", "stages", "questions"],
  caseStudyExhibit: ["id", "type", "title", "content", "visual"],
  caseStudyStage: ["id", "title", "trigger", "narrative", "timeOffset", "exhibits"],
  questionMeta: [
    "visual_justification",
    "derived_values_keyed",
    "expected_trend",
    "expected_flags",
    "expected_pattern",
    "pattern_keyed",
    "expected",
    "reference_bands",
    "keyed_cells",
    "keyed_relationship",
    "keyed_settings",
    "source",
    "tier",
    "skill_signature",
    "stem_disambiguators",
    "order",
    "weight_kg",
    "round",
    "shift_hours",
  ],
  expectedTrend: ["series", "vital", "direction", "window"],
  expectedFlag: ["series", "vital", "at", "flag"],
  referenceBand: ["series", "vital", "low", "high", "unit", "population"],
  caption: ["en", "zh"],
  visualCommon: ["kind", "caption"],
  visualByKind: {
    rhythm_strip: [
      "rhythm",
      "rateBpm",
      "durationSec",
      "seed",
      "calibrationPulse",
      "atrialRateBpm",
      "conductionRatio",
      "prSec",
      "qrsSec",
      "qtSec",
      "pacer",
    ],
    capnography: [
      "pattern",
      "etco2",
      "respiratoryRate",
      "durationSec",
      "severity",
      "baselineEtco2",
      "rosc",
    ],
    vitals_trend: ["timepointsHr", "time", "population", "series", "tempUnit"],
    lab_trend: ["time", "population", "series"],
    mar: ["timeGrid", "medications"],
    io_record: ["periodLabel", "intake", "output"],
    medication_label: [
      "drugName",
      "amount",
      "amountUnit",
      "perQty",
      "perUnit",
      "showDerivedConcentration",
      "fields",
    ],
    device_screen: ["device", "title", "settings"],
    fetal_monitoring: [
      "durationSec",
      "baselineFhr",
      "variability",
      "seed",
      "contractions",
      "accelerations",
      "decelerations",
    ],
    burn_map: ["population", "burns"],
    injection_site: ["route", "vessel"],
  },
  rosc: ["lowEtco2", "highEtco2", "stepAtSec"],
  visualTime: ["unit", "values"],
  vitalsSeries: ["vital", "values", "showReferenceBand"],
  labSeries: ["analyte", "values", "unit", "showReferenceBand"],
  marMedication: ["name", "dose", "route", "frequency", "administrations", "isHighAlert"],
  marAdministration: ["time", "status"],
  ioEntry: ["label", "volumeMl"],
  medLabelField: ["label", "value"],
  deviceSetting: ["key", "value", "text", "unit", "flag"],
  fetalContraction: ["peakSec", "amplitudeMmHg", "durationSec"],
  fetalAcceleration: ["peakSec", "riseBpm", "durationSec"],
  fetalDeceleration: ["type", "nadirSec", "depthBpm", "durationSec", "contractionIndex"],
} as const;

export type AllowedObjectType = {
  [Key in keyof typeof allowedKeySets]: typeof allowedKeySets[Key] extends readonly string[] ? Key : never;
}[keyof typeof allowedKeySets];

export const keysFor = (objectType: AllowedObjectType): ReadonlySet<string> =>
  new Set(allowedKeySets[objectType]);
